# Generated by Django 4.2.7 on 2025-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('sales_return', 'مردود مبيعات'), ('purchase_return', 'مردود مشتريات'), ('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف'), ('asset_depreciation', 'استهلاك الأصول'), ('manual', 'قيد يدوي'), ('adjustment', 'قيد تسوية')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
