# Generated by Django 4.2.7 on 2025-09-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['code', 'name'], 'permissions': [('view_journalaccount', 'Can view حساب')], 'verbose_name': 'حساب', 'verbose_name_plural': 'الحسابات'},
        ),
    ]
