# Generated by Django 4.2.7 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='creditor'),
        ),
    ]
