# Generated by Django 4.2.7 on 2025-09-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_salesinvoice_options_alter_salesreturn_options'),
        ('purchases', '0015_alter_purchasereturn_options'),
        ('journal', '0006_alter_journalline_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseinvoice', verbose_name='فاتورة المشتريات'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='فاتورة المبيعات'),
        ),
    ]
