# Generated by Django 4.2.7 on 2025-09-26 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0007_journalentry_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة المالية')),
                ('closing_date', models.DateField(verbose_name='تاريخ الإقفال')),
                ('net_profit', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='صافي الربح/الخسارة')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('closing_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_closing', to='journal.journalentry', verbose_name='قيد الإقفال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'إقفال سنوي',
                'verbose_name_plural': 'الإقفالات السنوية',
                'ordering': ['-year', '-closing_date'],
                'permissions': [('can_perform_year_end_closing', 'Can perform year end closing')],
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('year',)},
            },
        ),
    ]
