# Generated by Django 4.2.7 on 2025-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_yearendclosing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('receipt_voucher', 'Receipt Voucher'), ('payment_voucher', 'Payment Voucher'), ('revenue_expense', 'Revenue/Expense Entry'), ('asset_depreciation', 'Asset Depreciation'), ('provision', 'Provision'), ('provision_entry', 'Provision Entry'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
