# Generated by Django 4.2.7 on 2025-10-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-entry_date', '-created_at'], 'permissions': [('change_entry_number', 'تعديل رقم القيد')], 'verbose_name': 'قيد محاسبي', 'verbose_name_plural': 'القيود المحاسبية'},
        ),
    ]
