# Generated by Django 4.2.7 on 2025-10-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_bankreconciliation_bankstatement'),
        ('journal', '0011_journalentry_cashbox_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='bank_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.banktransfer', verbose_name='تحويل البنوك'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('receipt_voucher', 'Receipt Voucher'), ('payment_voucher', 'Payment Voucher'), ('revenue_expense', 'Revenue/Expense Entry'), ('asset_depreciation', 'Asset Depreciation'), ('provision', 'Provision'), ('provision_entry', 'Provision Entry'), ('cashbox_transfer', 'Cashbox Transfer'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
