# Generated by Django 4.2.7 on 2025-10-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_journalentry_bank_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('daily', 'قيد يومي'), ('closing', 'قيد إقفال'), ('adjustment', 'قيد تسوية'), ('opening', 'قيد افتتاحي'), ('transfer', 'قيد تحويل'), ('allocation', 'قيد توزيع'), ('revaluation', 'قيد إعادة تقييم'), ('other', 'قيد آخر')], default='daily', max_length=20, verbose_name='نوع القيد'),
        ),
    ]
