# Generated by Django 4.2.7 on 2025-10-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_journalentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'أصول'), ('liability', 'مطلوبات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصاريف'), ('purchases', 'مشتريات'), ('sales', 'مبيعات')], max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('daily', 'Daily'), ('other', 'Other')], default='daily', max_length=20, verbose_name='نوع القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('asset_depreciation', 'Asset Depreciation'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
