# Generated by Django 4.2.7 on 2025-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('asset_depreciation', 'Asset Depreciation'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry'), ('customer_supplier_adjustment', 'Customer/Supplier Balance Adjustment')], max_length=30, verbose_name='نوع العملية'),
        ),
    ]
