# Generated by Django 4.2.7 on 2025-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('asset_depreciation', 'Asset Depreciation'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry'), ('customer_supplier_adjustment', 'Customer/Supplier Balance Adjustment'), ('warehouse_transfer', 'Warehouse Transfer')], max_length=30, verbose_name='نوع العملية'),
        ),
    ]
