# Generated by Django 4.2.7 on 2025-10-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0014_banktransaction_adjustment_type_and_more'),
        ('cashboxes', '0017_alter_cashboxtransaction_options_and_more'),
        ('sales', '0020_alter_salescreditnote_options_and_more'),
        ('purchases', '0018_add_jofotara_verification_url_debitnote'),
        ('journal', '0016_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['code', 'name'], 'permissions': [('view_journalaccount', 'Can view Account')], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-entry_date', '-created_at'], 'permissions': [('change_entry_number', 'Change Entry Number')], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={'verbose_name': 'Journal Line', 'verbose_name_plural': 'Journal Lines'},
        ),
        migrations.AlterModelOptions(
            name='yearendclosing',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-year', '-closing_date'], 'permissions': [('can_perform_year_end_closing', 'Can perform year end closing')], 'verbose_name': 'Year End Closing', 'verbose_name_plural': 'Year End Closings'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesreturn', verbose_name='Sales Return'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Assets'), ('liability', 'Liabilities'), ('equity', 'Equity'), ('revenue', 'Revenues'), ('expense', 'Expenses'), ('purchases', 'Purchases'), ('sales', 'Sales')], max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='journal.account', verbose_name='Parent Account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='bank_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.banktransfer', verbose_name='Bank Transfer'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='cashbox_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashboxes.cashboxtransfer', verbose_name='Cashbox Transfer'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(verbose_name='Entry Description'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('daily', 'Daily'), ('other', 'Other')], default='daily', max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseinvoice', verbose_name='Purchase Invoice'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('asset_depreciation', 'Asset Depreciation'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry'), ('customer_supplier_adjustment', 'Customer/Supplier Balance Adjustment'), ('warehouse_transfer', 'Warehouse Transfer'), ('sales_return', 'Sales Return'), ('sales_return_cogs', 'Sales Return COGS')], max_length=30, verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='Sales Invoice'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='journal.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='line_description',
            field=models.TextField(blank=True, verbose_name='Line Description'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='closing_date',
            field=models.DateField(verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='closing_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_closing', to='journal.journalentry', verbose_name='Closing Entry'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='net_profit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Net Profit/Loss'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='year',
            field=models.IntegerField(verbose_name='Fiscal Year'),
        ),
    ]
