# Generated by Django 4.2.7 on 2025-10-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_add_jofotara_verification_url_debitnote'),
        ('journal', '0017_alter_account_options_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasereturn', verbose_name='Purchase Return'),
        ),
    ]
