# Generated by Django 4.2.7 on 2025-10-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0014_banktransaction_adjustment_type_and_more'),
        ('journal', '0018_journalentry_purchase_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_accounts', to='banks.bankaccount', verbose_name='Linked Bank Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Assets'), ('liability', 'Liabilities'), ('equity', 'Equity'), ('revenue', 'Revenues'), ('expense', 'Expenses'), ('purchases', 'Purchases')], max_length=20, verbose_name='Account Type'),
        ),
    ]
