# Generated by Django 4.2.7 on 2025-10-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_account_bank_account_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('asset_depreciation', 'Asset Depreciation'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment Entry'), ('customer_supplier_adjustment', 'Customer/Supplier Balance Adjustment'), ('warehouse_transfer', 'Warehouse Transfer'), ('sales_return', 'Sales Return'), ('sales_return_cogs', 'Sales Return COGS'), ('bank_transaction', 'Bank Transaction')], max_length=30, null=True, verbose_name='Reference Type'),
        ),
    ]
