# Generated by Django 4.2.7 on 2025-10-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_alter_journalentry_reference_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='reference_type',
        ),
    ]
