# Generated by Django 4.2.7 on 2025-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_remove_journalentry_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Reference Type'),
        ),
    ]
