# Generated by Django 4.2.7 on 2025-11-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_fiscalyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': [], 'ordering': ['code', 'name'], 'permissions': [('can_view_accounts', 'Can View Accounts'), ('can_add_accounts', 'Can Add Accounts'), ('can_edit_accounts', 'Can Edit Accounts'), ('can_delete_accounts', 'Can Delete Accounts')], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'default_permissions': [], 'ordering': ['-year'], 'permissions': [('can_open_fiscal_year', 'Can Open Fiscal Year'), ('can_access_closed_years', 'Can Access Closed Fiscal Years')], 'verbose_name': 'Fiscal Year', 'verbose_name_plural': 'Fiscal Years'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'default_permissions': [], 'ordering': ['-entry_date', '-created_at'], 'permissions': [('can_view_journal_entries', 'Can View Journal Entries'), ('can_add_journal_entries', 'Can Add Journal Entries'), ('can_edit_journal_entries', 'Can Edit Journal Entries'), ('can_delete_journal_entries', 'Can Delete Journal Entries')], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={'default_permissions': [], 'verbose_name': 'Journal Line', 'verbose_name_plural': 'Journal Lines'},
        ),
        migrations.AlterModelOptions(
            name='yearendclosing',
            options={'default_permissions': [], 'ordering': ['-year', '-closing_date'], 'permissions': [('can_perform_year_end_closing', 'Can Perform Year End Closing')], 'verbose_name': 'Year End Closing', 'verbose_name_plural': 'Year End Closings'},
        ),
    ]
