# Generated by Django 4.2.7 on 2025-11-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_alter_account_options_alter_fiscalyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_permissions': [], 'ordering': ['code', 'name'], 'permissions': [('can_view_accounts', 'View Chart of Accounts'), ('can_add_accounts', 'Add Account'), ('can_edit_accounts', 'Edit Account'), ('can_delete_accounts', 'Delete Account')], 'verbose_name': 'Chart of Accounts', 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'default_permissions': [], 'ordering': ['-year'], 'permissions': [('can_open_fiscal_year', 'Open Fiscal Year'), ('can_access_closed_years', 'Access Closed Fiscal Years')], 'verbose_name': 'Fiscal Year', 'verbose_name_plural': 'Fiscal Years'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'default_permissions': [], 'ordering': ['-entry_date', '-created_at'], 'permissions': [('can_view_journal_entries', 'View Journal Entries'), ('can_add_journal_entries', 'Add Journal Entry'), ('can_edit_journal_entries', 'Edit Journal Entry'), ('can_delete_journal_entries', 'Delete Journal Entry')], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='yearendclosing',
            options={'default_permissions': [], 'ordering': ['-year', '-closing_date'], 'permissions': [('can_perform_year_end_closing', 'Perform Year End Closing')], 'verbose_name': 'Year End Closing', 'verbose_name_plural': 'Year End Closings'},
        ),
    ]
