# Generated by Django 4.2.7 on 2025-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_alter_account_options_alter_fiscalyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'default_permissions': [], 'ordering': ['-year'], 'permissions': [('can_view_fiscal_years', 'View Fiscal Years'), ('can_add_fiscal_years', 'Add Fiscal Years'), ('can_edit_fiscal_years', 'Edit Fiscal Years'), ('can_delete_fiscal_years', 'Delete Fiscal Years'), ('can_open_fiscal_year', 'Open Fiscal Year')], 'verbose_name': 'Fiscal Year', 'verbose_name_plural': 'Fiscal Years'},
        ),
    ]
