# Generated by Django 4.2.7 on 2025-08-12 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_alter_bankaccount_options_and_more'),
        ('customers', '0003_alter_customersupplier_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashboxes', '0005_alter_cashbox_balance_alter_cashbox_created_at_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'ordering': ['-date', '-voucher_number'], 'verbose_name': 'Payment Voucher', 'verbose_name_plural': 'Payment Vouchers'},
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='banks.bankaccount', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transfer Reference'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='In case the beneficiary is not a registered supplier', max_length=200, verbose_name='Beneficiary Name'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='cashboxes.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='check_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='check_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Check Number'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='check_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Check Status'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='date',
            field=models.DateField(verbose_name='Voucher Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='Reversed'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer')], max_length=15, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='reversal_reason',
            field=models.TextField(blank=True, verbose_name='Reversal Reason'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reversal Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='customers.customersupplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Voucher Number'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_type',
            field=models.CharField(choices=[('supplier', 'Supplier Payment'), ('expense', 'Expenses'), ('salary', 'Salary'), ('other', 'Other')], max_length=20, verbose_name='Voucher Type'),
        ),
    ]
