# Generated by Django 4.2.7 on 2025-09-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentvoucher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'ordering': ['-date', '-voucher_number'], 'permissions': [('can_access_payments', 'يمكن الوصول إلى سندات الصرف')], 'verbose_name': 'Payment Voucher', 'verbose_name_plural': 'Payment Vouchers'},
        ),
    ]
