# Generated by Django 4.2.7 on 2025-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentvoucher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvoucher',
            options={'default_permissions': [], 'ordering': ['-date', '-voucher_number'], 'permissions': [('can_view_payments', 'Can View Payment Vouchers'), ('can_add_payments', 'Can Add Payment Vouchers'), ('can_edit_payments', 'Can Edit Payment Vouchers'), ('can_delete_payments', 'Can Delete Payment Vouchers')], 'verbose_name': 'Payment Voucher', 'verbose_name_plural': 'Payment Vouchers'},
        ),
    ]
