# Generated by Django 4.2.7 on 2025-07-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_pos',
            field=models.BooleanField(default=False, verbose_name='الوصول لنقطة البيع'),
        ),
        migrations.AddField(
            model_name='user',
            name='pos_only',
            field=models.BooleanField(default=False, verbose_name='نقطة البيع فقط'),
        ),
    ]
