# Generated by Django 4.2.7 on 2025-07-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_access_pos_user_pos_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_cashboxes',
            field=models.BooleanField(default=False, verbose_name='الوصول للصناديق النقدية'),
        ),
    ]
