# Generated by Django 4.2.7 on 2025-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_access_cashboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_receipts',
            field=models.BooleanField(default=False, verbose_name='الوصول لسندات القبض'),
        ),
    ]
