# Generated by Django 4.2.7 on 2025-08-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_can_access_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_company_settings',
            field=models.BooleanField(default=False, verbose_name='الوصول لإعدادات الشركة'),
        ),
    ]
