# Generated by Django 4.2.7 on 2025-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_can_access_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_system_management',
            field=models.BooleanField(default=False, verbose_name='الوصول لإدارة النظام'),
        ),
    ]
