# Generated by Django 4.2.7 on 2025-08-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_can_access_system_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_system_management', 'يمكنه الوصول لإدارة النظام')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
    ]
