# Generated by Django 4.2.7 on 2025-08-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_access_system_management',
        ),
    ]
