# Generated by Django 4.2.7 on 2025-08-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_can_access_system_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_system_management', 'يمكنه الوصول لإدارة النظام'), ('can_access_sales', 'يمكنه الوصول للمبيعات'), ('can_access_purchases', 'يمكنه الوصول للمشتريات'), ('can_access_inventory', 'يمكنه الوصول للمخزون'), ('can_access_banks', 'يمكنه الوصول للبنوك'), ('can_access_reports', 'يمكنه الوصول للتقارير'), ('can_access_pos', 'يمكنه الوصول لنقطة البيع'), ('can_access_company_settings', 'يمكنه الوصول لإعدادات الشركة'), ('can_delete_invoices', 'يمكنه حذف الفواتير'), ('can_edit_dates', 'يمكنه تعديل التواريخ'), ('can_edit_invoice_numbers', 'يمكنه تعديل أرقام الفواتير'), ('can_see_low_stock_alerts', 'يمكنه رؤية تنبيهات انخفاض المخزون'), ('cash_only_access', 'وصول كاش فقط'), ('credit_only_access', 'وصول ذمم فقط'), ('pos_only_access', 'نقطة البيع فقط')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_banks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_cashboxes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_company_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_inventory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_pos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_purchases',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_receipts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_sales',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_delete_invoices',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_dates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_invoice_numbers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_see_low_stock_alerts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cash_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_only',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pos_only',
        ),
    ]
