# Generated by Django 4.2.7 on 2025-08-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_remove_user_can_access_banks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_system_management', 'يمكنه الوصول لإدارة النظام'), ('can_manage_users', 'إدارة المستخدمين'), ('can_view_audit_logs', 'عرض سجلات المراجعة'), ('can_backup_system', 'نسخ احتياطي للنظام'), ('can_access_sales', 'يمكنه الوصول للمبيعات'), ('can_access_purchases', 'يمكنه الوصول للمشتريات'), ('can_access_inventory', 'يمكنه الوصول للمخزون'), ('can_access_banks', 'يمكنه الوصول للبنوك'), ('can_access_cashboxes', 'يمكنه الوصول للصناديق'), ('can_access_receipts', 'يمكنه الوصول للإيصالات'), ('can_access_reports', 'يمكنه الوصول للتقارير'), ('can_access_pos', 'يمكنه الوصول لنقطة البيع'), ('can_access_company_settings', 'يمكنه الوصول لإعدادات الشركة'), ('can_delete_invoices', 'يمكنه حذف الفواتير'), ('can_edit_dates', 'يمكنه تعديل التواريخ'), ('can_edit_invoice_numbers', 'يمكنه تعديل أرقام الفواتير'), ('can_see_low_stock_alerts', 'يمكنه رؤية تنبيهات انخفاض المخزون'), ('cash_only', 'كاش فقط'), ('credit_only', 'ذمم فقط'), ('pos_only', 'نقطة البيع فقط')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
    ]
