# Generated by Django 4.2.7 on 2025-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'مدير عام'), ('admin', 'مدير'), ('user', 'مستخدم'), ('pos_user', 'مستخدم نقطة بيع')], default='user', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
