# Generated by Django 4.2.7 on 2025-08-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('users', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_warehouse',
            field=models.ForeignKey(blank=True, help_text='المستودع المخصص لمستخدم نقطة البيع لإصدار الفواتير منه', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='مستودع نقطة البيع'),
        ),
    ]
