# Generated by Django 4.2.7 on 2025-08-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorymovement_created_at_and_more'),
        ('users', '0012_user_pos_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_system_management', 'Can access system management'), ('can_manage_users', 'Manage users'), ('can_view_audit_logs', 'View audit logs'), ('can_backup_system', 'System backup'), ('can_access_sales', 'Can access sales'), ('can_access_purchases', 'Can access purchases'), ('can_access_inventory', 'Can access inventory'), ('can_access_banks', 'Can access banks'), ('can_access_cashboxes', 'Can access cashboxes'), ('can_access_receipts', 'Can access receipts'), ('can_access_reports', 'Can access reports'), ('can_access_pos', 'Can access POS'), ('can_access_company_settings', 'Can access company settings'), ('can_delete_invoices', 'Can delete invoices'), ('can_edit_dates', 'Can edit dates'), ('can_edit_invoice_numbers', 'Can edit invoice numbers'), ('can_see_low_stock_alerts', 'Can see low stock alerts'), ('cash_only', 'Cash only'), ('credit_only', 'Credit only'), ('pos_only', 'POS only')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pos_warehouse',
            field=models.ForeignKey(blank=True, help_text='Dedicated warehouse for POS user to issue invoices from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='POS Warehouse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Manager'), ('user', 'User'), ('pos_user', 'POS User')], default='user', max_length=20, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='permissions',
            field=models.JSONField(default=dict, verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
