# Generated by Django 4.2.7 on 2025-09-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_system_management', 'Can access system management'), ('can_manage_users', 'Manage users'), ('can_view_audit_logs', 'View audit logs'), ('can_backup_system', 'System backup'), ('can_access_sales', 'Can access sales'), ('can_access_inventory', 'Can access inventory'), ('can_access_products', 'Can access products'), ('can_access_banks', 'Can access banks'), ('can_access_cashboxes', 'Can access cashboxes'), ('can_access_pos', 'Can access POS'), ('can_access_company_settings', 'Can access company settings'), ('can_delete_invoices', 'Can delete invoices'), ('can_delete_accounts', 'Can delete accounts'), ('can_edit_dates', 'Can edit dates'), ('can_edit_invoice_numbers', 'Can edit invoice numbers'), ('can_see_low_stock_alerts', 'Can see low stock alerts'), ('cash_only', 'Cash only'), ('credit_only', 'Credit only'), ('pos_only', 'POS only')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
