# Generated by Django 4.2.7 on 2025-09-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_options'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_group ADD COLUMN dashboard_sections JSON NULL;",
            reverse_sql="ALTER TABLE auth_group DROP COLUMN dashboard_sections;",
        ),
    ]
