# Generated by Django 4.2.7 on 2025-09-22 18:19

from django.db import migrations, connection


def change_column_type_sqlite(apps, schema_editor):
    """For SQLite, the column is already TEXT from the previous migration."""
    # No operation needed for SQLite
    pass


def reverse_change_column_type_sqlite(apps, schema_editor):
    """Reverse operation - no operation needed for SQLite."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_dashboard_sections_sql'),
    ]

    operations = [
        migrations.RunPython(
            change_column_type_sqlite,
            reverse_change_column_type_sqlite,
        ),
    ]
