# Generated by Django 4.2.7 on 2025-09-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_dashboard_sections_sql'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_group ALTER COLUMN dashboard_sections TYPE TEXT;",
            reverse_sql="ALTER TABLE auth_group ALTER COLUMN dashboard_sections TYPE JSON;",
        ),
    ]
