# Generated by Django 4.2.7 on 2025-09-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_change_dashboard_sections_to_text'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_group ADD COLUMN is_system_group BOOLEAN DEFAULT FALSE;",
            reverse_sql="ALTER TABLE auth_group DROP COLUMN is_system_group;"
        ),
    ]
