# Generated by Django 4.2.7 on 2025-09-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorymovement_product_and_more'),
        ('users', '0020_add_is_system_group_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_sales_warehouse',
            field=models.ForeignKey(blank=True, help_text='Default warehouse for sales invoices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sales_users', to='inventory.warehouse', verbose_name='Default Sales Warehouse'),
        ),
    ]
