# Generated by Django 4.2.7 on 2025-09-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorymovement_product_and_more'),
        ('users', '0021_user_default_sales_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pos_warehouse',
            field=models.ForeignKey(blank=True, help_text='Dedicated warehouse for POS user to issue invoices from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_users', to='inventory.warehouse', verbose_name='POS Warehouse'),
        ),
    ]
