# Generated by Django 4.2.7 on 2025-09-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0014_alter_cashbox_options_alter_cashbox_location_and_more'),
        ('users', '0023_user_default_purchase_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_cashbox',
            field=models.ForeignKey(blank=True, help_text='Default cash box for cash payments in invoices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='cashboxes.cashbox', verbose_name='Default Cash Box'),
        ),
    ]
