# Generated by Django 4.2.7 on 2025-11-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_users_list', 'Can View Users List'), ('can_add_users', 'Can Add Users'), ('can_edit_users', 'Can Edit Users'), ('can_delete_users', 'Can Delete Users'), ('can_view_groups_permissions', 'Can View Groups and Permissions'), ('can_add_groups_permissions', 'Can Add Groups and Permissions'), ('can_edit_groups_permissions', 'Can Edit Groups and Permissions'), ('can_delete_groups_permissions', 'Can Delete Groups and Permissions'), ('can_view_document_sequences', 'Can View Document Sequences'), ('can_edit_document_sequences', 'Can Edit Document Sequences'), ('can_view_system_settings', 'Can View System Settings'), ('can_edit_system_settings', 'Can Edit System Settings'), ('can_access_print_design', 'Can Access Print Design'), ('can_access_jofotara_settings', 'Can Access JoFotara Settings'), ('can_access_backup_system', 'Can Access Backup System'), ('can_access_system_management', 'Can access system management'), ('can_manage_users', 'Manage users'), ('can_view_audit_logs', 'View audit logs'), ('can_backup_system', 'System backup'), ('can_access_pos', 'Can access POS'), ('can_access_company_settings', 'Can access company settings'), ('can_delete_invoices', 'Can delete invoices'), ('can_edit_dates', 'Can edit dates'), ('can_edit_invoice_numbers', 'Can edit invoice numbers'), ('can_see_low_stock_alerts', 'Can see low stock alerts'), ('cash_only', 'Cash only'), ('credit_only', 'Credit only'), ('pos_only', 'POS only'), ('can_delete_accounts', 'Can delete accounts')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
