# Generated by Django 4.2.7 on 2025-11-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_pos', 'Can access POS'), ('can_delete_invoices', 'Can delete invoices'), ('can_edit_dates', 'Can edit dates'), ('can_edit_invoice_numbers', 'Can edit invoice numbers')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
