# Generated by Django 4.2.7 on 2025-11-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_users_list', 'View Users List'), ('can_view_groups_permissions', 'View Groups & Permissions'), ('can_view_activity_log', 'View Activity Log'), ('can_view_document_number_management', 'View Document Number Management'), ('can_view_system_settings', 'View System Settings'), ('can_access_pos', 'Can access POS'), ('can_delete_invoices', 'Can delete invoices'), ('can_edit_dates', 'Can edit dates'), ('can_edit_invoice_numbers', 'Can edit invoice numbers')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
