# Generated by Django 4.2.7 on 2025-11-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_users_list', 'View Users List'), ('can_view_groups_permissions', 'View Groups & Permissions'), ('can_view_activity_log', 'View Activity Log'), ('can_view_document_number_management', 'View Document Number Management'), ('can_view_system_settings', 'View System Settings'), ('can_add_user', 'Add User'), ('can_add_group', 'Add Group'), ('can_add_document_sequence', 'Add Document Sequence'), ('can_edit_user', 'Edit User'), ('can_edit_group', 'Edit Group'), ('can_edit_document_sequence', 'Edit Document Sequence'), ('can_delete_user', 'Delete User'), ('can_delete_group', 'Delete Group'), ('can_delete_document_sequence', 'Delete Document Sequence'), ('can_view_backup', 'View Backup and Restore'), ('can_make_backup', 'Make Backup'), ('can_restore_backup', 'Make Restore'), ('can_delete_all_data', 'Delete All Data'), ('can_access_pos', 'Can access POS'), ('can_delete_invoices', 'Can delete invoices'), ('can_edit_dates', 'Can edit dates'), ('can_edit_invoice_numbers', 'Can edit invoice numbers')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
