databases:
  - name: finspilot-db
    databaseName: finspilot_prod
    user: finspilot_user
    plan: free

services:
  - type: web
    name: finspilot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn finspilot.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: USE_LOCAL_POSTGRES
        value: false
      - key: DEFAULT_CURRENCY
        value: JOD
      - key: DATABASE_URL
        fromDatabase:
          name: finspilot-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false