services:
  - type: web
    name: finspilot
    env: python
    buildCommand: ""
    startCommand: gunicorn finspilot.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: finspilot.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: Finspilot.onrender.com
      - key: DB_NAME
        fromDatabase:
          name: finspilot-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: finspilot-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: finspilot-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: finspilot-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: finspilot-db
          property: port
      - key: RENDER
        value: True
databases:
  - name: finspilot-db
    databaseName: finspilot
    user: admin
