# Generated by Django 4.2.7 on 2025-07-11 12:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأصل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('purchase_cost', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='تكلفة الشراء')),
                ('current_value', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='القيمة الحالية')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مجمع الإهلاك')),
                ('salvage_value', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='القيمة التخريدية')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='المورد')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الضمان')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('maintenance', 'تحت الصيانة'), ('disposed', 'مستبعد'), ('sold', 'مباع')], default='active', max_length=20, verbose_name='الحالة')),
                ('depreciation_method', models.CharField(default='straight_line', max_length=50, verbose_name='طريقة الإهلاك')),
                ('last_depreciation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر إهلاك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'أصل',
                'verbose_name_plural': 'الأصول',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('type', models.CharField(choices=[('current', 'خصوم متداولة'), ('long_term', 'خصوم طويلة الأجل'), ('equity', 'حقوق الملكية')], max_length=20, verbose_name='نوع الخصم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'فئة الخصم',
                'verbose_name_plural': 'فئات الخصوم',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الخصم')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخصم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('original_amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='المبلغ الأصلي')),
                ('current_balance', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الرصيد الحالي')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل الفائدة %')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر دفعة')),
                ('creditor_name', models.CharField(max_length=200, verbose_name='اسم الدائن')),
                ('creditor_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='معلومات الاتصال')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العقد')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('paid', 'مسدد'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_liabilities.liabilitycategory', verbose_name='الفئة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'خصم',
                'verbose_name_plural': 'الخصوم',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depreciation_date', models.DateField(verbose_name='تاريخ الإهلاك')),
                ('depreciation_amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='مبلغ الإهلاك')),
                ('accumulated_depreciation_before', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مجمع الإهلاك قبل')),
                ('accumulated_depreciation_after', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مجمع الإهلاك بعد')),
                ('net_book_value_after', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='القيمة الدفترية بعد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_liabilities.asset', verbose_name='الأصل')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قيد إهلاك',
                'verbose_name_plural': 'قيود الإهلاك',
                'ordering': ['-depreciation_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('type', models.CharField(choices=[('current', 'أصول متداولة'), ('fixed', 'أصول ثابتة'), ('intangible', 'أصول غير ملموسة'), ('investment', 'استثمارات')], max_length=20, verbose_name='نوع الأصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل الإهلاك %')),
                ('useful_life_years', models.IntegerField(default=0, verbose_name='العمر الافتراضي بالسنوات')),
                ('is_depreciable', models.BooleanField(default=False, verbose_name='قابل للإهلاك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'فئة الأصل',
                'verbose_name_plural': 'فئات الأصول',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_liabilities.assetcategory', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='asset',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL, verbose_name='الشخص المسؤول'),
        ),
    ]
