# Generated by Django 4.2.7 on 2025-07-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('assets_liabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='liability',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.currency', verbose_name='العملة'),
        ),
    ]
