# Generated by Django 4.2.7 on 2025-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_liabilities', '0003_alter_asset_created_at_alter_asset_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier'),
        ),
    ]
