# Generated by Django 4.2.7 on 2025-10-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_journalentry_reference_type'),
        ('assets_liabilities', '0004_alter_asset_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AddField(
            model_name='liabilitycategory',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['liability', 'equity']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.account', verbose_name='الحساب المحاسبي'),
        ),
    ]
