# Generated by Django 4.2.7 on 2025-10-19 08:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_journalentry_purchase_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_liabilities', '0005_assetcategory_account_liabilitycategory_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='depreciationentry',
            options={'ordering': ['-depreciation_date'], 'verbose_name': 'Depreciation Entry', 'verbose_name_plural': 'Depreciation Entries'},
        ),
        migrations.AlterModelOptions(
            name='liability',
            options={'ordering': ['due_date'], 'verbose_name': 'Liability', 'verbose_name_plural': 'Liabilities'},
        ),
        migrations.AlterModelOptions(
            name='liabilitycategory',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Liability Category', 'verbose_name_plural': 'Liability Categories'},
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='accumulated_depreciation_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulated_depreciation_categories', to='journal.account', verbose_name='Accumulated Depreciation Account'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='depreciation_expense_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_expense_categories', to='journal.account', verbose_name='Depreciation Expense Account'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='accumulated_depreciation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Accumulated Depreciation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Asset Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_liabilities.assetcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(default='straight_line', max_length=50, verbose_name='Depreciation Method'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_depreciation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Depreciation Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Person'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Salvage Value'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('sold', 'Sold')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Expiry'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.account', verbose_name='Accounting Account'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Depreciation Rate %'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='is_depreciable',
            field=models.BooleanField(default=False, verbose_name='Depreciable'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='type',
            field=models.CharField(choices=[('current', 'Current Assets'), ('fixed', 'Fixed Assets'), ('intangible', 'Intangible Assets'), ('investment', 'Investments')], max_length=20, verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='useful_life_years',
            field=models.IntegerField(default=0, verbose_name='Useful Life Years'),
        ),
        migrations.AlterField(
            model_name='depreciationentry',
            name='accumulated_depreciation_after',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Accumulated Depreciation After'),
        ),
        migrations.AlterField(
            model_name='depreciationentry',
            name='accumulated_depreciation_before',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Accumulated Depreciation Before'),
        ),
        migrations.AlterField(
            model_name='depreciationentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_liabilities.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='depreciationentry',
            name='depreciation_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Depreciation Amount'),
        ),
        migrations.AlterField(
            model_name='depreciationentry',
            name='depreciation_date',
            field=models.DateField(verbose_name='Depreciation Date'),
        ),
        migrations.AlterField(
            model_name='depreciationentry',
            name='net_book_value_after',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Net Book Value After'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_liabilities.liabilitycategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='creditor_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Information'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='creditor_name',
            field=models.CharField(max_length=200, verbose_name='Creditor Name'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='current_balance',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Interest Rate %'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='liability_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Liability Number'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Liability Name'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='original_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Original Amount'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='liabilitycategory',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['liability', 'equity']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.account', verbose_name='Accounting Account'),
        ),
        migrations.AlterField(
            model_name='liabilitycategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='liabilitycategory',
            name='type',
            field=models.CharField(choices=[('current', 'Current Liabilities'), ('long_term', 'Long-term Liabilities'), ('equity', 'Equity')], max_length=20, verbose_name='Liability Type'),
        ),
    ]
