# Generated by Django 4.2.7 on 2025-11-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_liabilities', '0006_alter_asset_options_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'default_permissions': [], 'ordering': ['-purchase_date'], 'permissions': [('can_view_assets', 'View Assets'), ('can_add_assets', 'Add Assets'), ('can_edit_assets', 'Edit Assets'), ('can_delete_assets', 'Delete Assets')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'permissions': [('can_view_asset_categories', 'View Asset Categories'), ('can_add_asset_categories', 'Add Asset Categories'), ('can_edit_asset_categories', 'Edit Asset Categories'), ('can_delete_asset_categories', 'Delete Asset Categories')], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='liability',
            options={'default_permissions': [], 'ordering': ['due_date'], 'permissions': [('can_view_liabilities', 'View Liabilities'), ('can_add_liabilities', 'Add Liabilities'), ('can_edit_liabilities', 'Edit Liabilities'), ('can_delete_liabilities', 'Delete Liabilities')], 'verbose_name': 'Liability', 'verbose_name_plural': 'Liabilities'},
        ),
        migrations.AlterModelOptions(
            name='liabilitycategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'permissions': [('can_view_liability_categories', 'View Liability Categories'), ('can_add_liability_categories', 'Add Liability Categories'), ('can_edit_liability_categories', 'Edit Liability Categories'), ('can_delete_liability_categories', 'Delete Liability Categories')], 'verbose_name': 'Liability Category', 'verbose_name_plural': 'Liability Categories'},
        ),
    ]
