# Generated by Django 4.2.7 on 2025-11-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_liabilities', '0007_alter_asset_options_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciationentry',
            options={'default_permissions': [], 'ordering': ['-depreciation_date'], 'verbose_name': 'Depreciation Entry', 'verbose_name_plural': 'Depreciation Entries'},
        ),
    ]
