# Generated by Django 4.2.7 on 2025-11-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_liabilities', '0008_alter_depreciationentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciationentry',
            options={'default_permissions': [], 'ordering': ['-depreciation_date'], 'permissions': [('can_view_depreciation_entries', 'View Depreciation Entries'), ('can_add_depreciation_entries', 'Add Depreciation Entries'), ('can_edit_depreciation_entries', 'Edit Depreciation Entries'), ('can_delete_depreciation_entries', 'Delete Depreciation Entries')], 'verbose_name': 'Depreciation Entry', 'verbose_name_plural': 'Depreciation Entries'},
        ),
    ]
