# Generated by Django 4.2.7 on 2025-11-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_liabilities', '0009_alter_depreciationentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'default_permissions': [], 'ordering': ['-purchase_date'], 'permissions': [('can_view_assets_liabilities', 'Can View Assets/Liabilities'), ('can_add_assets_liabilities', 'Can Add Assets/Liabilities'), ('can_edit_assets_liabilities', 'Can Edit Assets/Liabilities'), ('can_delete_assets_liabilities', 'Can Delete Assets/Liabilities')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='depreciationentry',
            options={'default_permissions': [], 'ordering': ['-depreciation_date'], 'verbose_name': 'Depreciation Entry', 'verbose_name_plural': 'Depreciation Entries'},
        ),
        migrations.AlterModelOptions(
            name='liability',
            options={'default_permissions': [], 'ordering': ['due_date'], 'verbose_name': 'Liability', 'verbose_name_plural': 'Liabilities'},
        ),
        migrations.AlterModelOptions(
            name='liabilitycategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'verbose_name': 'Liability Category', 'verbose_name_plural': 'Liability Categories'},
        ),
    ]
