# Generated by Django 4.2.7 on 2025-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('view', 'عرض')], max_length=20, verbose_name='نوع العملية')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
            ],
            options={
                'verbose_name': 'سجل المراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Triangle', max_length=200, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='شعار الشركة')),
                ('currency', models.CharField(default='JOD', max_length=10, verbose_name='العملة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sales_invoice', 'فاتورة المبيعات'), ('sales_return', 'مردود المبيعات'), ('purchase_invoice', 'فاتورة المشتريات'), ('purchase_return', 'مردود المشتريات'), ('bank_transfer', 'التحويل بين الحسابات البنكية'), ('bank_cash_transfer', 'التحويل بين البنوك والصناديق'), ('journal_entry', 'القيود المحاسبية'), ('warehouse_transfer', 'التحويل بين المستودعات'), ('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف')], max_length=50, unique=True, verbose_name='نوع المستند')),
                ('prefix', models.CharField(default='', max_length=10, verbose_name='البادئة')),
                ('digits', models.PositiveIntegerField(default=6, verbose_name='عدد الخانات')),
                ('current_number', models.PositiveIntegerField(default=1, verbose_name='الرقم الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تسلسل أرقام المستندات',
                'verbose_name_plural': 'تسلسل أرقام المستندات',
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'انخفاض المخزون'), ('system_alert', 'تنبيه النظام'), ('user_action', 'إجراء المستخدم')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار النظام',
                'verbose_name_plural': 'إشعارات النظام',
                'ordering': ['-created_at'],
            },
        ),
    ]
