# Generated by Django 4.2.7 on 2025-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_documentsequence_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة المبيعات'), ('pos_invoice', 'فاتورة نقطة البيع'), ('sales_return', 'مردود المبيعات'), ('purchase_invoice', 'فاتورة المشتريات'), ('purchase_return', 'مردود المشتريات'), ('bank_transfer', 'التحويل بين الحسابات البنكية'), ('bank_cash_transfer', 'التحويل بين البنوك والصناديق'), ('cashbox_transfer', 'التحويل بين الصناديق'), ('journal_entry', 'القيود المحاسبية'), ('warehouse_transfer', 'التحويل بين المستودعات'), ('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف')], max_length=50, unique=True, verbose_name='نوع المستند'),
        ),
    ]
