# Generated by Django 4.2.7 on 2025-07-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_documentsequence_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_audit_log', 'يمكن عرض سجل الأنشطة')], 'verbose_name': 'سجل المراجعة', 'verbose_name_plural': 'سجلات المراجعة'},
        ),
    ]
