# Generated by Django 4.2.7 on 2025-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد'), ('reset', 'إعادة تعيين')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
