# Generated by Django 4.2.7 on 2025-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_session_timeout',
            field=models.BooleanField(default=True, help_text='تفعيل إنهاء الجلسة تلقائياً عند عدم النشاط', verbose_name='تفعيل انتهاء الجلسة التلقائي'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logout_on_browser_close',
            field=models.BooleanField(default=True, help_text='إنهاء الجلسة تلقائياً عند إغلاق المتصفح', verbose_name='تسجيل الخروج عند إغلاق المتصفح'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='مدة عدم النشاط قبل إنهاء الجلسة تلقائياً (بالدقائق)', verbose_name='مدة انتهاء الجلسة (بالدقائق)'),
        ),
    ]
