# Generated by Django 4.2.7 on 2025-10-16 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة الافتراضية'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة المبيعات'), ('pos_invoice', 'فاتورة نقطة البيع'), ('sales_return', 'مردود المبيعات'), ('credit_note', 'إشعار دائن'), ('debit_note', 'إشعار مدين'), ('purchase_invoice', 'فاتورة المشتريات'), ('purchase_return', 'مردود المشتريات'), ('bank_transfer', 'التحويل بين الحسابات البنكية'), ('bank_cash_transfer', 'التحويل بين البنوك والصناديق'), ('cashbox_transfer', 'التحويل بين الصناديق'), ('journal_entry', 'القيود المحاسبية'), ('warehouse_transfer', 'Transfer Between Warehouses'), ('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف')], max_length=50, unique=True, verbose_name='نوع المستند'),
        ),
    ]
