# Generated by Django 4.2.7 on 2025-10-24 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_companysettings_default_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_audit_log', 'Can view audit log')], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Company Settings', 'verbose_name_plural': 'Company Settings'},
        ),
        migrations.AlterModelOptions(
            name='documentsequence',
            options={'verbose_name': 'Document Sequences', 'verbose_name_plural': 'Document Sequences'},
        ),
        migrations.AlterModelOptions(
            name='systemnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'System Notification', 'verbose_name_plural': 'System Notifications'},
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enable_integrity_checks',
            field=models.BooleanField(default=True, help_text='تفعيل الفحوصات التلقائية لسلامة البيانات المحاسبية', verbose_name='Enable Data Integrity Checks'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='integrity_check_frequency',
            field=models.PositiveIntegerField(default=24, help_text='عدد الساعات بين كل فحص لسلامة البيانات', verbose_name='Integrity Check Frequency (Hours)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('reset', 'Reset')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(max_length=100, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(default='FinsPilot', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Default Tax Rate'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='enable_session_timeout',
            field=models.BooleanField(default=True, help_text='تفعيل إنهاء الجلسة تلقائياً عند عدم النشاط', verbose_name='Enable Automatic Session Timeout'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logout_on_browser_close',
            field=models.BooleanField(default=True, help_text='إنهاء الجلسة تلقائياً عند إغلاق المتصفح', verbose_name='Logout on Browser Close'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='مدة عدم النشاط قبل إنهاء الجلسة تلقائياً (بالدقائق)', verbose_name='Session Timeout (Minutes)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='current_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Current Number'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='digits',
            field=models.PositiveIntegerField(default=6, verbose_name='Number of Digits'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('pos_invoice', 'POS Invoice'), ('sales_return', 'Sales Return'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_return', 'Purchase Return'), ('bank_transfer', 'Bank Account Transfer'), ('bank_cash_transfer', 'Bank to Cashbox Transfer'), ('cashbox_transfer', 'Cashbox Transfer'), ('journal_entry', 'Journal Entries'), ('warehouse_transfer', 'Transfer Between Warehouses'), ('receipt_voucher', 'Receipt Voucher'), ('payment_voucher', 'Payment Voucher')], max_length=50, unique=True, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='prefix',
            field=models.CharField(default='', max_length=10, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('system_alert', 'System Alert'), ('user_action', 'User Action')], max_length=20, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
