# Generated by Django 4.2.7 on 2025-11-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_auditlog_options_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('access', 'Access'), ('export', 'Export'), ('import', 'Import'), ('reset', 'Reset')], max_length=20, verbose_name='Action Type'),
        ),
    ]
