# Generated by Django 4.2.7 on 2025-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='enable_integrity_checks',
            field=models.BooleanField(default=True, help_text='Enable automatic checks for accounting data integrity', verbose_name='Enable Data Integrity Checks'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='enable_session_timeout',
            field=models.BooleanField(default=True, help_text='Enable automatic session termination on inactivity', verbose_name='Enable Automatic Session Timeout'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='integrity_check_frequency',
            field=models.PositiveIntegerField(default=24, help_text='Number of hours between each data integrity check', verbose_name='Integrity Check Frequency (Hours)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logout_on_browser_close',
            field=models.BooleanField(default=True, help_text='Automatic session termination when browser is closed', verbose_name='Logout on Browser Close'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Inactivity duration before automatic session termination (in minutes)', verbose_name='Session Timeout (Minutes)'),
        ),
    ]
