# Generated by Django 4.2.7 on 2025-07-09 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0004_remove_default_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصندوق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='الرصيد')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الصندوق')),
            ],
            options={
                'verbose_name': 'صندوق نقدي',
                'verbose_name_plural': 'الصناديق النقدية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashboxTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('transfer_type', models.CharField(choices=[('cashbox_to_cashbox', 'من صندوق إلى صندوق'), ('cashbox_to_bank', 'من صندوق إلى بنك'), ('bank_to_cashbox', 'من بنك إلى صندوق')], max_length=20, verbose_name='نوع التحويل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='المبلغ')),
                ('fees', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='الرسوم')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='سعر الصرف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_transfers_from', to='banks.bankaccount', verbose_name='من البنك')),
                ('from_cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='cashboxes.cashbox', verbose_name='من الصندوق')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_transfers_to', to='banks.bankaccount', verbose_name='إلى البنك')),
                ('to_cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='cashboxes.cashbox', verbose_name='إلى الصندوق')),
            ],
            options={
                'verbose_name': 'تحويل صندوق',
                'verbose_name_plural': 'تحويلات الصناديق',
                'ordering': ['-date', '-transfer_number'],
            },
        ),
        migrations.CreateModel(
            name='CashboxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('initial_balance', 'رصيد افتتاحي'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashboxes.cashbox', verbose_name='الصندوق')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashboxes.cashboxtransfer', verbose_name='التحويل المرتبط')),
            ],
            options={
                'verbose_name': 'حركة صندوق',
                'verbose_name_plural': 'حركات الصناديق',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
