# Generated by Django 4.2.7 on 2025-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0002_alter_cashboxtransfer_from_cashbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtransfer',
            name='from_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم البنك المرسل'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='from_cashbox_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الصندوق المرسل'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='to_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم البنك المستقبل'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='to_cashbox_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الصندوق المستقبل'),
        ),
    ]
