# Generated by Django 4.2.7 on 2025-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0003_cashboxtransfer_from_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtransfer',
            name='check_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم بنك الشيك'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الشيك'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الشيك'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='deposit_document_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم مستند الإيداع'),
        ),
        migrations.AddField(
            model_name='cashboxtransfer',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('cash', 'نقداً'), ('check', 'شيك')], max_length=10, verbose_name='نوع الإيداع'),
        ),
    ]
