# Generated by Django 4.2.7 on 2025-08-12 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashboxes', '0004_cashboxtransfer_check_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('initial_balance', 'رصيد افتتاحي'), ('adjustment', 'تسوية')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='fees',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='transfer_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Transfer Number'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
