# Generated by Django 4.2.7 on 2025-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0005_alter_cashbox_balance_alter_cashbox_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='check_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Check Bank Name'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Date'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Check Number'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='deposit_document_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Deposit Document Number'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check')], max_length=10, verbose_name='Deposit Type'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('cashbox_to_cashbox', 'Cashbox to Cashbox'), ('cashbox_to_bank', 'Cashbox to Bank'), ('bank_to_cashbox', 'Bank to Cashbox')], max_length=20, verbose_name='نوع التحويل'),
        ),
    ]
