# Generated by Django 4.2.7 on 2025-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0006_alter_cashboxtransfer_check_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('initial_balance', 'رصيد افتتاحي'), ('adjustment', 'settlement')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
