# Generated by Django 4.2.7 on 2025-09-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0007_alter_cashboxtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'permissions': [('can_edit_cashboxes', 'يمكن تعديل الصناديق النقدية')], 'verbose_name': 'صندوق نقدي', 'verbose_name_plural': 'الصناديق النقدية'},
        ),
    ]
