# Generated by Django 4.2.7 on 2025-09-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0009_alter_cashbox_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'permissions': [('can_add_cashboxes', 'يمكن إضافة الصناديق النقدية'), ('can_edit_cashboxes', 'يمكن تعديل الصناديق النقدية'), ('can_delete_cashboxes', 'يمكن حذف الصناديق النقدية')], 'verbose_name': 'صندوق نقدي', 'verbose_name_plural': 'الصناديق النقدية'},
        ),
    ]
