# Generated by Django 4.2.7 on 2025-09-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0011_fix_cashbox_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'permissions': [('can_view_cashboxes', 'يمكن عرض الصناديق النقدية'), ('can_add_cashboxes', 'يمكن إضافة الصناديق النقدية'), ('can_edit_cashboxes', 'يمكن تعديل الصناديق النقدية'), ('can_delete_cashboxes', 'يمكن حذف الصناديق النقدية')], 'verbose_name': 'صندوق نقدي', 'verbose_name_plural': 'الصناديق النقدية'},
        ),
    ]
