# Generated by Django 4.2.7 on 2025-09-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0012_add_view_cashbox_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'permissions': [('can_view_cashboxes', 'يمكن عرض الصناديق النقدية'), ('can_add_cashboxes', 'يمكن إضافة الصناديق النقدية'), ('can_edit_cashboxes', 'يمكن تعديل الصناديق النقدية'), ('can_delete_cashboxes', 'يمكن حذف الصناديق النقدية'), ('can_modify_cashbox', 'تعديل صندوق')], 'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Boxes'},
        ),
    ]
