# Generated by Django 4.2.7 on 2025-09-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashboxes', '0013_alter_cashbox_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'permissions': [('can_view_cashboxes', 'Cash boxes can be displayed'), ('can_add_cashboxes', 'Cash boxes can be added'), ('can_edit_cashboxes', 'Cash boxes can be edited'), ('can_delete_cashboxes', 'Cash boxes can be deleted'), ('can_modify_cashbox', 'Cash box can be modified')], 'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Boxes'},
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Cash Box Name'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsible User'),
        ),
    ]
