# Generated by Django 4.2.7 on 2025-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0014_alter_cashbox_options_alter_cashbox_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtransaction',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reference ID'),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('receipt', 'سند قبض'), ('payment', 'سند دفع'), ('transfer', 'تحويل')], max_length=50, verbose_name='Reference Type'),
        ),
    ]
