# Generated by Django 4.2.7 on 2025-10-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0015_cashboxtransaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('capital', 'Capital Contribution'), ('error_correction', 'Error Correction'), ('cash_shortage', 'Cash Shortage'), ('cash_surplus', 'Cash Surplus'), ('reconciliation', 'Cash Reconciliation'), ('other', 'Other')], help_text='Type of manual adjustment (IFRS compliant)', max_length=50, null=True, verbose_name='Adjustment Type'),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='is_manual_adjustment',
            field=models.BooleanField(default=False, help_text='Is this a manual balance adjustment?', verbose_name='Manual Adjustment'),
        ),
    ]
