# Generated by Django 4.2.7 on 2025-10-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0014_banktransaction_adjustment_type_and_more'),
        ('cashboxes', '0016_cashboxtransaction_adjustment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashboxtransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Cashbox Transaction', 'verbose_name_plural': 'Cashbox Transactions'},
        ),
        migrations.AlterModelOptions(
            name='cashboxtransfer',
            options={'ordering': ['-date', '-transfer_number'], 'verbose_name': 'Cashbox Transfer', 'verbose_name_plural': 'Cashbox Transfers'},
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashboxes.cashbox', verbose_name='Cash Box'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('transfer', 'Transfer')], max_length=50, verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='related_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashboxes.cashboxtransfer', verbose_name='Related Transfer'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('initial_balance', 'Initial Balance'), ('adjustment', 'settlement')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='from_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_transfers_from', to='banks.bankaccount', verbose_name='From Bank'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='from_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sender Bank Name'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='from_cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='cashboxes.cashbox', verbose_name='From Cashbox'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='from_cashbox_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sender Cashbox Name'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='to_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_transfers_to', to='banks.bankaccount', verbose_name='To Bank'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='to_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Receiver Bank Name'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='to_cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='cashboxes.cashbox', verbose_name='To Cashbox'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='to_cashbox_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Receiver Cashbox Name'),
        ),
        migrations.AlterField(
            model_name='cashboxtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('cashbox_to_cashbox', 'Cashbox to Cashbox'), ('cashbox_to_bank', 'Cashbox to Bank'), ('bank_to_cashbox', 'Bank to Cashbox')], max_length=20, verbose_name='Transfer Type'),
        ),
    ]
