# Generated by Django 4.2.7 on 2025-11-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0017_alter_cashboxtransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Boxes'},
        ),
    ]
