# Generated by Django 4.2.7 on 2025-11-15 06:59

from django.db import migrations


def create_cashbox_permissions(apps, schema_editor):
    """إنشاء صلاحيات الصناديق النقدية"""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Cashbox = apps.get_model('cashboxes', 'Cashbox')
    
    # الحصول على ContentType للصناديق
    cashbox_ct = ContentType.objects.get_for_model(Cashbox)
    
    # قائمة الصلاحيات التي سيتم إنشاؤها
    permissions = [
        ('add_cashbox', 'Can add صندوق نقدي'),
        ('change_cashbox', 'Can change صندوق نقدي'),
        ('delete_cashbox', 'Can delete صندوق نقدي'),
        ('view_cashbox', 'Can view صندوق نقدي'),
    ]
    
    # إنشاء الصلاحيات إذا لم تكن موجودة
    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            content_type=cashbox_ct,
            defaults={'name': name}
        )


def delete_cashbox_permissions(apps, schema_editor):
    """حذف صلاحيات الصناديق النقدية"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Cashbox = apps.get_model('cashboxes', 'Cashbox')
    
    cashbox_ct = ContentType.objects.get_for_model(Cashbox)
    
    # حذف الصلاحيات
    Permission.objects.filter(
        content_type=cashbox_ct,
        codename__in=['add_cashbox', 'change_cashbox', 'delete_cashbox', 'view_cashbox']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0018_alter_cashbox_options'),
    ]

    operations = [
        migrations.RunPython(create_cashbox_permissions, delete_cashbox_permissions),
    ]
