# Generated by Django 4.2.7 on 2025-11-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0019_add_cashbox_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'permissions': [('can_view_cashbox', 'Can View Cash Box')], 'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Boxes'},
        ),
    ]
