# Generated by Django 4.2.7 on 2025-11-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0021_remove_can_view_cashbox_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_cashboxes', 'Can View Cash Boxes'), ('can_add_cashboxes', 'Can Add Cash Boxes'), ('can_edit_cashboxes', 'Can Edit Cash Boxes'), ('can_delete_cashboxes', 'Can Delete Cash Boxes')], 'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Boxes'},
        ),
        migrations.AlterModelOptions(
            name='cashboxtransaction',
            options={'default_permissions': [], 'ordering': ['-date', '-created_at'], 'verbose_name': 'Cashbox Transaction', 'verbose_name_plural': 'Cashbox Transactions'},
        ),
        migrations.AlterModelOptions(
            name='cashboxtransfer',
            options={'default_permissions': [], 'ordering': ['-date', '-transfer_number'], 'verbose_name': 'Cashbox Transfer', 'verbose_name_plural': 'Cashbox Transfers'},
        ),
    ]
