# Generated by Django 4.2.7 on 2025-11-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0023_alter_cashbox_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_cashboxes', 'Can View Cash Boxes'), ('can_add_cashboxes', 'Can Add Cash Boxes'), ('can_create_cashboxes_transfers', 'Can Create Cashbox Transfers'), ('can_edit_cashboxes', 'Can Edit Cash Boxes'), ('can_delete_cashboxes', 'Can Delete Cash Boxes')], 'verbose_name': 'Cash Box', 'verbose_name_plural': 'Cash Boxes'},
        ),
    ]
