# Generated by Django 4.2.7 on 2026-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Analytics Permissions',
                'verbose_name_plural': 'Analytics Permissions',
                'permissions': [('view_ai_dashboard', 'Can View AI Dashboard'), ('view_sales_analytics', 'Can View Sales Analytics'), ('view_purchase_analytics', 'Can View Purchase Analytics'), ('view_tax_analytics', 'Can View Tax Analytics'), ('view_cashflow_analytics', 'Can View Cash Flow Analytics'), ('export_analytics_reports', 'Can Export Analytics Reports')],
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
