# Generated by Django 4.2.7 on 2025-07-09 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السند')),
                ('date', models.DateField(verbose_name='تاريخ السند')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('check', 'شيك')], max_length=10, verbose_name='نوع الدفع')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='المبلغ')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الشيك')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشيك')),
                ('check_due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق الشيك')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='اسم البنك')),
                ('check_status', models.CharField(blank=True, choices=[('pending', 'في الانتظار'), ('collected', 'تم التحصيل'), ('bounced', 'مرتد'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الشيك')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='مُعكوس')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ العكس')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='سبب العكس')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='cashboxes.cashbox', verbose_name='الصندوق النقدي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='customers.customersupplier', verbose_name='العميل')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_receipts', to=settings.AUTH_USER_MODEL, verbose_name='عُكس بواسطة')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-date', '-receipt_number'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_date', models.DateField(verbose_name='تاريخ العكس')),
                ('reason', models.TextField(verbose_name='سبب العكس')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('original_receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='receipts.paymentreceipt', verbose_name='السند الأصلي')),
            ],
            options={
                'verbose_name': 'عكس سند قبض',
                'verbose_name_plural': 'عكس سندات القبض',
                'ordering': ['-reversal_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='تاريخ التحصيل')),
                ('status', models.CharField(choices=[('collected', 'تم التحصيل'), ('bounced', 'مرتد')], max_length=20, verbose_name='حالة التحصيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashboxes.cashbox', verbose_name='الصندوق النقدي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='receipts.paymentreceipt', verbose_name='سند القبض')),
            ],
            options={
                'verbose_name': 'تحصيل شيك',
                'verbose_name_plural': 'تحصيل الشيكات',
                'ordering': ['-collection_date'],
            },
        ),
    ]
