# Generated by Django 4.2.7 on 2025-09-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_checkcollection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'ordering': ['-date', '-receipt_number'], 'permissions': [('can_access_receipts', 'يمكن الوصول إلى سندات القبض')], 'verbose_name': 'سند قبض', 'verbose_name_plural': 'سندات القبض'},
        ),
    ]
