# Generated by Django 4.2.7 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_paymentreceipt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='bounce_reason',
            field=models.CharField(blank=True, help_text='سبب ارتداد الشيك (رصيد غير كافٍ، توقيع غير صحيح، إيقاف من البنك...)', max_length=100, verbose_name='سبب الارتداد'),
        ),
    ]
