# Generated by Django 4.2.7 on 2025-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_paymentreceipt_bounce_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='ecl_calculation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ حساب ECL'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='ecl_calculation_method',
            field=models.CharField(blank=True, help_text='طريقة حساب الخسارة المتوقعة (مرتد، متأخر، إلخ)', max_length=50, verbose_name='طريقة حساب ECL'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='expected_credit_loss',
            field=models.DecimalField(decimal_places=3, default=0, help_text='قيمة الخسارة المتوقعة وفق IFRS 9', max_digits=15, verbose_name='خسائر الائتمان المتوقعة (ECL)'),
        ),
    ]
