# Generated by Django 4.2.7 on 2025-09-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customersupplier_options'),
        ('receipts', '0006_paymentreceipt_ecl_calculation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='customers.customersupplier', verbose_name='Customer'),
        ),
    ]
