# Generated by Django 4.2.7 on 2025-10-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_bankreconciliation_bankstatement'),
        ('receipts', '0007_alter_paymentreceipt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='banks.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='bank_transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التحويل البنكي'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='bank_transfer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات التحويل البنكي'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='bank_transfer_reference',
            field=models.CharField(blank=True, help_text='رقم مرجع التحويل البنكي أو رقم العملية', max_length=100, verbose_name='رقم مرجع التحويل'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('check', 'شيك'), ('bank_transfer', 'تحويل بنكي')], max_length=20, verbose_name='نوع الدفع'),
        ),
    ]
