# Generated by Django 4.2.7 on 2025-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_paymentreceipt_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'default_permissions': [], 'ordering': ['-date', '-receipt_number'], 'permissions': [('can_view_receipts', 'Can View Receipt Vouchers'), ('can_add_receipts', 'Can Add Receipt Vouchers'), ('can_edit_receipts', 'Can Edit Receipt Vouchers'), ('can_delete_receipts', 'Can Delete Receipt Vouchers')], 'verbose_name': 'سند قبض', 'verbose_name_plural': 'سندات القبض'},
        ),
    ]
