# Generated by Django 4.2.7 on 2025-11-15 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0020_alter_bankaccount_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashboxes', '0023_alter_cashbox_options'),
        ('receipts', '0009_alter_paymentreceipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkcollection',
            options={'ordering': ['-collection_date'], 'verbose_name': 'Check Collection', 'verbose_name_plural': 'Check Collections'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'default_permissions': [], 'ordering': ['-date', '-receipt_number'], 'permissions': [('can_view_receipts', 'Can View Receipt Vouchers'), ('can_add_receipts', 'Can Add Receipt Vouchers'), ('can_edit_receipts', 'Can Edit Receipt Vouchers'), ('can_delete_receipts', 'Can Delete Receipt Vouchers')], 'verbose_name': 'Receipt Voucher', 'verbose_name_plural': 'Receipt Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='receiptreversal',
            options={'ordering': ['-reversal_date'], 'verbose_name': 'Receipt Reversal', 'verbose_name_plural': 'Receipt Reversals'},
        ),
        migrations.AlterField(
            model_name='checkcollection',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashboxes.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='checkcollection',
            name='collection_date',
            field=models.DateField(verbose_name='Collection Date'),
        ),
        migrations.AlterField(
            model_name='checkcollection',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='receipts.paymentreceipt', verbose_name='Receipt Voucher'),
        ),
        migrations.AlterField(
            model_name='checkcollection',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('bounced', 'Bounced')], max_length=20, verbose_name='Collection Status'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='banks.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='bank_transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bank Transfer Date'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='bank_transfer_notes',
            field=models.TextField(blank=True, verbose_name='Bank Transfer Notes'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='bank_transfer_reference',
            field=models.CharField(blank=True, help_text='Bank transfer reference or transaction id', max_length=100, verbose_name='Bank Transfer Reference'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='bounce_reason',
            field=models.CharField(blank=True, help_text='Reason for cheque bounce (insufficient funds, signature mismatch, bank stop payment...)', max_length=100, verbose_name='Bounce Reason'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='cashboxes.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='check_cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_receipts', to='cashboxes.cashbox', verbose_name='Check Cashbox'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Date'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='check_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Check Number'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='check_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('collected', 'Collected'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Check Status'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='date',
            field=models.DateField(verbose_name='Receipt Date'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='ecl_calculation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ECL Calculation Date'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='ecl_calculation_method',
            field=models.CharField(blank=True, help_text='Method used to calculate expected credit loss (reversal, overdue, etc)', max_length=50, verbose_name='ECL Calculation Method'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='expected_credit_loss',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Value of expected credit loss (ECL)', max_digits=15, verbose_name='Expected Credit Loss (ECL)'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='Reversed'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='reversal_reason',
            field=models.TextField(blank=True, verbose_name='Reversal Reason'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reversal Date'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By'),
        ),
        migrations.AlterField(
            model_name='receiptreversal',
            name='original_receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='receipts.paymentreceipt', verbose_name='Original Receipt'),
        ),
        migrations.AlterField(
            model_name='receiptreversal',
            name='reason',
            field=models.TextField(verbose_name='Reversal Reason'),
        ),
        migrations.AlterField(
            model_name='receiptreversal',
            name='reversal_date',
            field=models.DateField(verbose_name='Reversal Date'),
        ),
    ]
