# Generated by Django 4.2.7 on 2025-11-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_alter_checkcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkcollection',
            options={'default_permissions': [], 'ordering': ['-collection_date'], 'verbose_name': 'Check Collection', 'verbose_name_plural': 'Check Collections'},
        ),
        migrations.AlterModelOptions(
            name='receiptreversal',
            options={'default_permissions': [], 'ordering': ['-reversal_date'], 'verbose_name': 'Receipt Reversal', 'verbose_name_plural': 'Receipt Reversals'},
        ),
    ]
