# Generated by Django 4.2.7 on 2025-11-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_alter_paymentreceipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'default_permissions': [], 'ordering': ['-date', '-receipt_number'], 'permissions': [('can_view_receipts', 'Can View Receipt Vouchers'), ('can_add_receipts', 'Can Add Receipt Vouchers'), ('can_edit_receipts', 'Can Edit Receipt Vouchers'), ('can_delete_receipts', 'Can Delete Receipt Vouchers'), ('can_view_check_management', 'Can View Cheque Management'), ('can_collect_checks', 'Can Collect Cheques'), ('can_view_check_balance_forecast', 'Can View Check Balance Forecast')], 'verbose_name': 'Receipt Voucher', 'verbose_name_plural': 'Receipt Vouchers'},
        ),
    ]
