# Generated by Django 4.2.7 on 2025-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bankaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='العملة'),
        ),
    ]
