# Generated by Django 4.2.7 on 2025-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الرصيد الأولي للحساب عند بداية التشغيل', max_digits=15, verbose_name='الرصيد الأولي'),
        ),
    ]
