# Generated by Django 4.2.7 on 2025-08-12 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0006_bankaccount_initial_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Bank Transaction', 'verbose_name_plural': 'Bank Transactions'},
        ),
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'ordering': ['-date', '-transfer_number'], 'verbose_name': 'Bank Transfer', 'verbose_name_plural': 'Bank Transfers'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Initial account balance at the start of operations', max_digits=15, verbose_name='Initial Balance'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='SWIFT Code'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='banks.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='fees',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='banks.bankaccount', verbose_name='From Account'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='banks.bankaccount', verbose_name='To Account'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='transfer_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Transfer Number'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
