# Generated by Django 4.2.7 on 2025-08-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'permissions': [('can_view_banks_account', 'Can View Banks Account')], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
