# Generated by Django 4.2.7 on 2025-08-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_alter_bankaccount_options_bankaccount_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'permissions': [('can_view_banks_account', 'Can View Banks Account'), ('can_edit_banks_account', 'Can Edit Banks Account'), ('can_delete_banks_account', 'Can Delete Banks Account')], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
