# Generated by Django 4.2.7 on 2025-09-26 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0011_alter_bankaccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(verbose_name='Statement Date')),
                ('book_balance', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Book Balance')),
                ('statement_balance', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Statement Balance')),
                ('reconciled_balance', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Reconciled Balance')),
                ('difference', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Difference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('deposits_in_transit', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Deposits in Transit')),
                ('outstanding_checks', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Outstanding Checks')),
                ('bank_charges', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Bank Charges')),
                ('interest_earned', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Interest Earned')),
                ('other_adjustments', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Other Adjustments')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banks.bankaccount', verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Statement Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('debit', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Credit')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Balance')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciled')),
                ('reconciled_date', models.DateTimeField(blank=True, null=True, verbose_name='Reconciled Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='banks.bankaccount', verbose_name='Bank Account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('bank_account', 'date', 'reference')},
            },
        ),
    ]
