# Generated by Django 4.2.7 on 2025-10-13 09:40

from django.db import migrations


def update_bank_transaction_reference_numbers(apps, schema_editor):
    BankTransaction = apps.get_model('banks', 'BankTransaction')
    
    # التحقق من وجود تطبيق cashboxes
    try:
        CashboxTransfer = apps.get_model('cashboxes', 'CashboxTransfer')
    except LookupError:
        # إذا لم يكن التطبيق موجوداً بعد، نتجاهل هذه الهجرة
        return
    
    # تحديث BankTransaction للتحويلات بين البنك والصناديق
    for transaction in BankTransaction.objects.filter(description__contains='شيك:'):
        # استخراج رقم الشيك من الوصف
        import re
        match = re.search(r'شيك:\s*(\S+)', transaction.description)
        if match:
            check_number = match.group(1)
            # البحث عن CashboxTransfer بالشيك ورقم الحساب والمبلغ والتاريخ
            transfers = CashboxTransfer.objects.filter(
                description__contains=f'شيك رقم: {check_number}',
                date=transaction.date,
                created_by=transaction.created_by
            )
            for transfer in transfers:
                # التحقق من مطابقة الحساب والمبلغ تقريباً
                if ((hasattr(transfer, 'from_bank') and transfer.from_bank == transaction.bank) or
                    (hasattr(transfer, 'to_bank') and transfer.to_bank == transaction.bank)):
                    # التحقق من المبلغ (مع مراعاة الرسوم)
                    expected_amount = transfer.amount
                    if transfer.fees and transaction.transaction_type == 'withdrawal':
                        expected_amount += transfer.fees
                    if abs(transaction.amount - expected_amount) < 0.01:
                        # تحديث reference_number
                        transaction.reference_number = transfer.transfer_number
                        transaction.save()
                        break


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_bankreconciliation_bankstatement'),
    ]

    operations = [
        migrations.RunPython(update_bank_transaction_reference_numbers),
    ]
