# Generated by Django 4.2.7 on 2025-10-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0013_update_bank_transaction_reference_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('capital', 'Capital Contribution'), ('error_correction', 'Error Correction'), ('bank_interest', 'Bank Interest'), ('bank_charges', 'Bank Charges'), ('reconciliation', 'Bank Reconciliation'), ('exchange_difference', 'Exchange Difference'), ('other', 'Other')], help_text='Type of manual adjustment (IFRS compliant)', max_length=50, null=True, verbose_name='Adjustment Type'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_manual_adjustment',
            field=models.BooleanField(default=False, help_text='Is this a manual balance adjustment?', verbose_name='Manual Adjustment'),
        ),
    ]
