# Generated by Django 4.2.7 on 2025-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0014_banktransaction_adjustment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='is_opening_balance',
            field=models.BooleanField(default=False, help_text='Is this an opening balance transaction?', verbose_name='Opening Balance'),
        ),
    ]
