# Generated by Django 4.2.7 on 2025-11-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0015_banktransaction_is_opening_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
