# Generated by Django 4.2.7 on 2025-11-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0016_alter_bankaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'default_permissions': [], 'ordering': ['name'], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
