# Generated by Django 4.2.7 on 2025-11-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0017_alter_bankaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'default_permissions': [], 'ordering': ['-statement_date', '-created_at'], 'verbose_name': 'Bank Reconciliation', 'verbose_name_plural': 'Bank Reconciliations'},
        ),
        migrations.AlterModelOptions(
            name='bankstatement',
            options={'default_permissions': [], 'ordering': ['-date', '-created_at'], 'verbose_name': 'Bank Statement', 'verbose_name_plural': 'Bank Statements'},
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'default_permissions': [], 'ordering': ['-date', '-created_at'], 'verbose_name': 'Bank Transaction', 'verbose_name_plural': 'Bank Transactions'},
        ),
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'default_permissions': [], 'ordering': ['-date', '-transfer_number'], 'verbose_name': 'Bank Transfer', 'verbose_name_plural': 'Bank Transfers'},
        ),
    ]
