# Generated by Django 4.2.7 on 2025-11-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0018_alter_bankreconciliation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_bank_accounts', 'Can View Bank Accounts')], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
