# Generated by Django 4.2.7 on 2025-11-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0019_alter_bankaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_bank_accounts', 'Can View Bank Accounts'), ('can_add_bank_accounts', 'Can Add Bank Accounts'), ('can_edit_bank_accounts', 'Can Edit Bank Accounts'), ('can_delete_bank_accounts', 'Can Delete Bank Accounts')], 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
    ]
