# Generated by Django 4.2.7 on 2025-07-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المردود')),
                ('date', models.DateField(verbose_name='تاريخ المردود')),
                ('return_type', models.CharField(choices=[('full', 'مردود كامل'), ('partial', 'مردود جزئي')], default='partial', max_length=20, verbose_name='نوع المردود')),
                ('return_reason', models.CharField(choices=[('defective', 'منتج معيب'), ('wrong_item', 'صنف خاطئ'), ('excess', 'فائض عن الحاجة'), ('expired', 'منتهي الصلاحية'), ('damaged', 'تالف أثناء النقل'), ('other', 'أخرى')], max_length=20, verbose_name='سبب المردود')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المجموع الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseinvoice', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مردود مشتريات',
                'verbose_name_plural': 'مردودات المشتريات',
                'ordering': ['-date', '-return_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='سعر الوحدة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseinvoiceitem', verbose_name='العنصر الأصلي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn', verbose_name='مردود المشتريات')),
            ],
            options={
                'verbose_name': 'عنصر مردود مشتريات',
                'verbose_name_plural': 'عناصر مردود المشتريات',
            },
        ),
    ]
