# Generated by Django 4.2.7 on 2025-07-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchases', '0003_purchasereturn_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المستودع'),
        ),
    ]
