# Generated by Django 4.2.7 on 2025-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchasedebitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebitnote',
            name='jofotara_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when debit note was sent to JoFotara', null=True, verbose_name='Sent to JoFotara At'),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='jofotara_uuid',
            field=models.CharField(blank=True, help_text='UUID returned from JoFotara API', max_length=100, null=True, verbose_name='JoFotara UUID'),
        ),
    ]
