# Generated by Django 4.2.7 on 2025-09-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_add_jofotara_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedebitnote',
            options={'ordering': ['-date', '-note_number'], 'permissions': (('can_send_to_jofotara', 'Can send debit notes to JoFotara'),), 'verbose_name': 'اشعار مدين', 'verbose_name_plural': 'اشعارات مدين'},
        ),
    ]
