# Generated by Django 4.2.7 on 2025-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_purchasedebitnote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_tax_inclusive',
            field=models.BooleanField(default=True, help_text='عند الاختيار، ستكون الأسعار شاملة للضريبة', verbose_name='شامل ضريبة'),
        ),
    ]
