# Generated by Django 4.2.7 on 2025-09-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_add_is_tax_inclusive_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-date', '-return_number'], 'verbose_name': 'Purchase Return', 'verbose_name_plural': 'Purchase Returns'},
        ),
    ]
