# Generated by Django 4.2.7 on 2025-09-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_purchaseinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': [('can_view_purchases', 'Can View Purchase')], 'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
    ]
