# Generated by Django 4.2.7 on 2025-09-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_purchaseinvoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedebitnote',
            options={'ordering': ['-date', '-note_number'], 'permissions': (('can_send_to_jofotara', 'Can send debit notes to JoFotara'), ('can_view_debitnote', 'Can view اشعار مدين')), 'verbose_name': 'اشعار مدين', 'verbose_name_plural': 'اشعارات مدين'},
        ),
    ]
