# Generated by Django 4.2.7 on 2025-09-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_alter_purchasedebitnote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-date', '-return_number'], 'permissions': (('can_view_purchasereturn', 'Can view مردود مشتريات'),), 'verbose_name': 'Purchase Return', 'verbose_name_plural': 'Purchase Returns'},
        ),
    ]
