# Generated by Django 4.2.7 on 2025-09-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_purchasereturn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': [('can_view_purchases', 'Can View Purchase'), ('can_view_purchase_statement', 'Can View Purchase Statement')], 'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
    ]
