# Generated by Django 4.2.7 on 2025-09-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorymovement_product_and_more'),
        ('customers', '0006_alter_customersupplier_options'),
        ('products', '0025_alter_category_code_alter_category_name_en_and_more'),
        ('purchases', '0015_alter_purchasereturn_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedebitnote',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
    ]
