# Generated by Django 4.2.7 on 2025-10-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_alter_purchaseinvoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebitnote',
            name='jofotara_verification_url',
            field=models.URLField(blank=True, help_text='URL to verify debit note on JoFotara portal', null=True, verbose_name='JoFotara Verification URL'),
        ),
    ]
