# Generated by Django 4.2.7 on 2025-10-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_add_jofotara_verification_url_debitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebitnote',
            name='supplier_debit_note_number',
            field=models.CharField(blank=True, help_text='رقم إشعار المدين الصادر من المورد', max_length=50, verbose_name='رقم إشعار المدين (مصدر)'),
        ),
    ]
