# Generated by Django 4.2.7 on 2025-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_purchasedebitnote_supplier_debit_note_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='supplier_debit_note_number',
            field=models.CharField(help_text='رقم إشعار المدين الصادر من المورد', max_length=50, verbose_name='رقم إشعار المدين (مصدر)'),
        ),
    ]
