# Generated by Django 4.2.7 on 2025-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_alter_purchasedebitnote_supplier_debit_note_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier_return_number',
            field=models.CharField(default=1, help_text='رقم مردود المشتريات الصادر من المورد', max_length=50, verbose_name='رقم مردود المشتريات (مصدر)'),
            preserve_default=False,
        ),
    ]
