# Generated by Django 4.2.7 on 2025-10-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customersupplier_options_and_more'),
        ('purchases', '0021_purchasereturn_supplier_return_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedebitnote',
            options={'ordering': ['-date', '-note_number'], 'permissions': (('can_send_to_jofotara', 'Can send debit notes to JoFotara'), ('can_view_debitnote', 'Can view debit notes')), 'verbose_name': 'Debit Note', 'verbose_name_plural': 'Debit Notes'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': [('can_view_purchases', 'Can View Purchase'), ('can_view_purchase_statement', 'Can View Purchase Statement'), ('can_toggle_purchase_tax', 'Can Toggle Purchase Tax Inclusive')], 'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoiceitem',
            options={'verbose_name': 'Purchase Invoice Item', 'verbose_name_plural': 'Purchase Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-date', '-return_number'], 'permissions': (('can_view_purchasereturn', 'Can view purchase returns'),), 'verbose_name': 'Purchase Return', 'verbose_name_plural': 'Purchase Returns'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnitem',
            options={'verbose_name': 'Purchase Return Item', 'verbose_name_plural': 'Purchase Return Items'},
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='note_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Debit Note Number'),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='supplier_debit_note_number',
            field=models.CharField(help_text='The debit note number issued by the supplier', max_length=50, verbose_name='Supplier Debit Note Number (Source)'),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='is_tax_inclusive',
            field=models.BooleanField(default=True, help_text='When selected, prices will include tax', verbose_name='Tax Inclusive'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'type__in': ['supplier', 'both']}, on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(max_length=50, verbose_name='Supplier Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseinvoice', verbose_name='Original Invoice'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Return Number'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_reason',
            field=models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item'), ('excess', 'Excess Quantity'), ('expired', 'Expired'), ('damaged', 'Damaged During Transport'), ('other', 'Other')], max_length=20, verbose_name='Return Reason'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_type',
            field=models.CharField(choices=[('full', 'Full Return'), ('partial', 'Partial Return')], default='partial', max_length=20, verbose_name='Return Type'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='supplier_return_number',
            field=models.CharField(help_text='The return number issued by the supplier', max_length=50, verbose_name='Supplier Return Number (Source)'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='original_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseinvoiceitem', verbose_name='Original Item'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='return_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn', verbose_name='Purchase Return'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Returned Quantity'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Unit Price'),
        ),
    ]
