# Generated by Django 4.2.7 on 2025-10-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0017_alter_cashboxtransaction_options_and_more'),
        ('banks', '0014_banktransaction_adjustment_type_and_more'),
        ('purchases', '0022_alter_purchasedebitnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banks.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashboxes.cashbox', verbose_name='Cash Box'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check Date'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Check Number'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Payment'), ('check', 'Check Payment'), ('transfer', 'Bank Transfer')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
