# Generated by Django 4.2.7 on 2025-10-31 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0023_add_payment_method_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Payment'), ('check', 'Check Payment'), ('transfer', 'Bank Transfer'), ('credit', 'Credit Payment')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='purchases.purchaseinvoice', verbose_name='Original Invoice'),
        ),
    ]
