# Generated by Django 4.2.7 on 2025-11-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0024_change_return_foreign_key_to_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedebitnote',
            options={'default_permissions': [], 'ordering': ['-date', '-note_number'], 'verbose_name': 'Debit Note', 'verbose_name_plural': 'Debit Notes'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'default_permissions': [], 'ordering': ['-date', '-invoice_number'], 'permissions': [('can_view_purchases', 'Can View Purchases'), ('can_add_purchases', 'Can Add Purchases'), ('can_edit_purchases', 'Can Edit Purchases'), ('can_delete_purchases', 'Can Delete Purchases')], 'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoiceitem',
            options={'default_permissions': [], 'verbose_name': 'Purchase Invoice Item', 'verbose_name_plural': 'Purchase Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'default_permissions': [], 'ordering': ['-date', '-return_number'], 'permissions': [('can_view_purchase_returns', 'Can View Purchase Returns'), ('can_add_purchase_returns', 'Can Add Purchase Returns'), ('can_edit_purchase_returns', 'Can Edit Purchase Returns'), ('can_delete_purchase_returns', 'Can Delete Purchase Returns')], 'verbose_name': 'Purchase Return', 'verbose_name_plural': 'Purchase Returns'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnitem',
            options={'default_permissions': [], 'verbose_name': 'Purchase Return Item', 'verbose_name_plural': 'Purchase Return Items'},
        ),
    ]
