# Generated by Django 4.2.7 on 2025-11-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0026_alter_purchasedebitnote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedebitnote',
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-date', '-note_number'],
                'default_permissions': [],
                'permissions': [
                    ('can_view_debit_notes', 'Can View Debit Notes'),
                    ('can_add_debit_notes', 'Can Add Debit Notes'),
                    ('can_edit_debit_notes', 'Can Edit Debit Notes'),
                    ('can_delete_debit_notes', 'Can Delete Debit Notes'),
                ],
            },
        ),
    ]
