# Generated by Django 4.2.7 on 2025-11-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0027_update_debitnote_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={
                'default_permissions': [],
                'ordering': ['-date', '-invoice_number'],
                'permissions': [
                    ('can_view_purchases', 'Can View Purchases'),
                    ('can_add_purchases', 'Can Add Purchases'),
                    ('can_edit_purchases', 'Can Edit Purchases'),
                    ('can_delete_purchases', 'Can Delete Purchases'),
                    ('can_view_purchase_statement', 'Can View Purchase Statement'),
                ],
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices'
            },
        ),
    ]
