# Generated by Django 4.2.7 on 2025-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0028_update_purchase_statement_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebitnote',
            name='is_posted_to_tax',
            field=models.BooleanField(default=False, help_text='Whether this debit note has been successfully posted to tax authority', verbose_name='Posted to Tax Authority'),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='jofotara_qr_code',
            field=models.TextField(blank=True, help_text='QR Code image data URL from JoFotara', null=True, verbose_name='JoFotara QR Code'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_posted_to_tax',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been successfully posted to tax authority', verbose_name='Posted to Tax Authority'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='jofotara_qr_code',
            field=models.TextField(blank=True, help_text='QR Code image data URL from JoFotara', null=True, verbose_name='JoFotara QR Code'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='jofotara_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when invoice was sent to JoFotara', null=True, verbose_name='Sent to JoFotara At'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='jofotara_uuid',
            field=models.CharField(blank=True, help_text='UUID returned from JoFotara API', max_length=100, null=True, verbose_name='JoFotara UUID'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='jofotara_verification_url',
            field=models.URLField(blank=True, help_text='URL to verify invoice on JoFotara portal', null=True, verbose_name='JoFotara Verification URL'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='is_posted_to_tax',
            field=models.BooleanField(default=False, help_text='Whether this return has been successfully posted to tax authority', verbose_name='Posted to Tax Authority'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='jofotara_qr_code',
            field=models.TextField(blank=True, help_text='QR Code image data URL from JoFotara', null=True, verbose_name='JoFotara QR Code'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='jofotara_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when return was sent to JoFotara', null=True, verbose_name='Sent to JoFotara At'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='jofotara_uuid',
            field=models.CharField(blank=True, help_text='UUID returned from JoFotara API', max_length=100, null=True, verbose_name='JoFotara UUID'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='jofotara_verification_url',
            field=models.URLField(blank=True, help_text='URL to verify return on JoFotara portal', null=True, verbose_name='JoFotara Verification URL'),
        ),
    ]
