# Generated by Django 4.2.7 on 2025-12-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee__first_name'], 'permissions': [('view_hr_attendance', 'Can View Attendance'), ('add_hr_attendance', 'Can Add Attendance'), ('change_hr_attendance', 'Can Change Attendance'), ('delete_hr_attendance', 'Can Delete Attendance')], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date'], 'permissions': [('view_hr_contract', 'Can View Contracts'), ('add_hr_contract', 'Can Add Contracts'), ('change_hr_contract', 'Can Change Contracts'), ('delete_hr_contract', 'Can Delete Contracts')], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'permissions': [('view_hr_department', 'Can View Departments'), ('add_hr_department', 'Can Add Departments'), ('change_hr_department', 'Can Change Departments'), ('delete_hr_department', 'Can Delete Departments')], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('view_hr_menu', 'Can View HR Menu'), ('view_hr_employee', 'Can View Employees'), ('add_hr_employee', 'Can Add Employees'), ('change_hr_employee', 'Can Change Employees'), ('delete_hr_employee', 'Can Delete Employees')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-upload_date'], 'permissions': [('view_hr_employeedocument', 'Can View Employee Documents'), ('add_hr_employeedocument', 'Can Add Employee Documents'), ('change_hr_employeedocument', 'Can Change Employee Documents'), ('delete_hr_employeedocument', 'Can Delete Employee Documents')], 'verbose_name': 'Employee Document', 'verbose_name_plural': 'Employee Documents'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('view_hr_leaverequest', 'Can View Leave Requests'), ('add_hr_leaverequest', 'Can Add Leave Requests'), ('change_hr_leaverequest', 'Can Change Leave Requests'), ('delete_hr_leaverequest', 'Can Delete Leave Requests'), ('approve_hr_leaverequest', 'Can Approve Leave Requests')], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name'], 'permissions': [('view_hr_leavetype', 'Can View Leave Types'), ('add_hr_leavetype', 'Can Add Leave Types'), ('change_hr_leavetype', 'Can Change Leave Types'), ('delete_hr_leavetype', 'Can Delete Leave Types')], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AlterModelOptions(
            name='payrollentry',
            options={'ordering': ['-payroll_period__start_date', 'employee__first_name'], 'permissions': [('view_hr_payrollentry', 'Can View Payroll Entries'), ('add_hr_payrollentry', 'Can Add Payroll Entries'), ('change_hr_payrollentry', 'Can Change Payroll Entries'), ('delete_hr_payrollentry', 'Can Delete Payroll Entries')], 'verbose_name': 'Payroll Entry', 'verbose_name_plural': 'Payroll Entries'},
        ),
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-start_date'], 'permissions': [('view_hr_payrollperiod', 'Can View Payroll Periods'), ('add_hr_payrollperiod', 'Can Add Payroll Periods'), ('change_hr_payrollperiod', 'Can Change Payroll Periods'), ('delete_hr_payrollperiod', 'Can Delete Payroll Periods'), ('process_hr_payrollperiod', 'Can Process Payroll Periods')], 'verbose_name': 'Payroll Period', 'verbose_name_plural': 'Payroll Periods'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['department__name', 'title'], 'permissions': [('view_hr_position', 'Can View Positions'), ('add_hr_position', 'Can Add Positions'), ('change_hr_position', 'Can Change Positions'), ('delete_hr_position', 'Can Delete Positions')], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
    ]
