# Generated by Django 4.2.7 on 2025-12-04 07:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_attendance_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_social_security_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.75'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Company Social Security Rate %'),
        ),
        migrations.AddField(
            model_name='employee',
            name='withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Withholding Tax Rate %'),
        ),
    ]
