# Generated by Django 4.2.7 on 2025-12-04 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_company_social_security_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='probation_period_days',
            field=models.IntegerField(default=0, help_text='Number of days for probation period. 0 means no probation.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Probation Period (Days)'),
        ),
    ]
