# Generated by Django 4.2.7 on 2025-12-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_probation_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_terminated',
            field=models.BooleanField(default=False, verbose_name='Is Terminated'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_notes',
            field=models.TextField(blank=True, verbose_name='Termination Notes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.CharField(blank=True, choices=[('dismissal', 'Dismissal'), ('resignation', 'Resignation'), ('retirement', 'Retirement')], max_length=20, null=True, verbose_name='Termination Reason'),
        ),
    ]
