# Generated by Django 4.2.7 on 2025-12-04 08:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_is_terminated_employee_termination_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='additional_deduction_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Additional Deduction Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_deduction_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', max_length=20, verbose_name='Additional Deduction Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_deduction_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Additional Deduction Value'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_additional_deductions',
            field=models.BooleanField(default=False, verbose_name='Has Additional Deductions'),
        ),
    ]
