# Generated by Django 4.2.7 on 2025-12-04 08:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_employee_additional_deduction_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Deduction Name')),
                ('deduction_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', max_length=20, verbose_name='Deduction Type')),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Deduction Value')),
                ('notes', models.TextField(blank=True, verbose_name='Deduction Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deductions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Deduction',
                'verbose_name_plural': 'Employee Deductions',
                'ordering': ['employee', '-created_at'],
                'permissions': [('view_hr_employeededuction', 'Can View Employee Deductions'), ('add_hr_employeededuction', 'Can Add Employee Deductions'), ('change_hr_employeededuction', 'Can Change Employee Deductions'), ('delete_hr_employeededuction', 'Can Delete Employee Deductions')],
            },
        ),
    ]
