# Generated by Django 4.2.7 on 2025-12-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_add_employee_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='additional_deduction_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='additional_deduction_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='additional_deduction_value',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_additional_deductions',
        ),
    ]
