# Generated by Django 4.2.7 on 2025-07-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحركة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('transaction_type', models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('sales_return', 'مردود مبيعات'), ('purchase_return', 'مردود مشتريات'), ('payment', 'دفعة'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('direction', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='الاتجاه')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='المبلغ')),
                ('reference_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='الرصيد بعد الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customersupplier', verbose_name='العميل/المورد')),
            ],
            options={
                'verbose_name': 'حركة حساب',
                'verbose_name_plural': 'حركات الحسابات',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['customer_supplier', 'date'], name='accounts_ac_custome_6cecda_idx'), models.Index(fields=['transaction_type', 'date'], name='accounts_ac_transac_c566cf_idx'), models.Index(fields=['reference_type', 'reference_id'], name='accounts_ac_referen_3ca957_idx')],
            },
        ),
    ]
