# Generated by Django 4.2.7 on 2025-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('sales_return', 'مردود مبيعات'), ('purchase_return', 'مردود مشتريات'), ('debit_note', 'مذكرة دين'), ('credit_note', 'مذكرة ائتمان'), ('payment', 'سند دفع'), ('receipt', 'سند قبض'), ('adjustment', 'تسوية')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
