# Generated by Django 4.2.7 on 2025-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounttransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note'), ('payment', 'Payment Voucher'), ('receipt', 'Receipt Voucher'), ('adjustment', 'settlement')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
