# Generated by Django 4.2.7 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounttransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='direction',
            field=models.CharField(choices=[('debit', 'مدين'), ('credit', 'creditor')], max_length=10, verbose_name='الاتجاه'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Movement Number'),
        ),
    ]
