# Generated by Django 4.2.7 on 2025-10-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounttransaction_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('capital_contribution', 'مساهمة رأسمالية'), ('error_correction', 'تصحيح خطأ'), ('bad_debt_write_off', 'شطب ديون معدومة'), ('discount_allowed', 'خصم مسموح به'), ('discount_received', 'خصم مستلم'), ('revaluation', 'إعادة تقييم'), ('other', 'أخرى')], help_text='Type of manual adjustment (IFRS compliant)', max_length=50, null=True, verbose_name='نوع التعديل'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='is_manual_adjustment',
            field=models.BooleanField(default=False, help_text='Is this a manual balance adjustment?', verbose_name='تعديل يدوي'),
        ),
    ]
