# Generated by Django 4.2.7 on 2025-10-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customersupplier_options_and_more'),
        ('accounts', '0006_accounttransaction_adjustment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Account Transaction', 'verbose_name_plural': 'Account Transactions'},
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('capital_contribution', 'Capital Contribution'), ('error_correction', 'Error Correction'), ('bad_debt_write_off', 'Bad Debt Write-off'), ('discount_allowed', 'Discount Allowed'), ('discount_received', 'Discount Received'), ('revaluation', 'Revaluation'), ('other', 'Other')], help_text='Type of manual adjustment (IFRS compliant)', max_length=50, null=True, verbose_name='Adjustment Type'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Balance After Transaction'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='customer_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customersupplier', verbose_name='Customer/Supplier'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='direction',
            field=models.CharField(choices=[('debit', 'debtor'), ('credit', 'creditor')], max_length=10, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='is_manual_adjustment',
            field=models.BooleanField(default=False, help_text='Is this a manual balance adjustment?', verbose_name='Manual Adjustment'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Reference Type'),
        ),
    ]
