# Generated by Django 4.2.7 on 2026-06-14 13:53

#from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounttransaction_options_and_more'),
    ]

    operations = [
    ]
