# Generated by Django 4.2.7 on 2026-06-14 13:53

#from django.db import migrations


#class Migration(migrations.Migration):

    #dependencies = [
    #    ('accounts', '0007_alter_accounttransaction_options_and_more'),
    #]

    #operations = [
    #]

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        # تأكد من أنك تضع هنا اسم آخر ملف هجرة فعلي كان موجوداً في 'accounts' قبل هذا الملف
        ('accounts', '0007_alter_accounttransaction_options_and_more'), 
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='dashboard_sections',
            field=models.TextField(blank=True, null=True),
        ),
    ]