# Generated by Django 4.2.7 on 2026-06-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_group_dashboard_sections_group_is_system_group'),
        ('accounts', '0007_alter_accounttransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_sections', models.TextField(blank=True, help_text='Comma separated list of sections', null=True, verbose_name='Dashboard Sections')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Settings',
            },
        ),
    ]
