# Generated by Django 4.2.7 on 2025-07-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SAR', 'الريال السعودي'), ('USD', 'الدولار الأمريكي'), ('EUR', 'اليورو'), ('GBP', 'الجنيه الإسترليني'), ('JOD', 'الدينار الأردني'), ('AED', 'الدرهم الإماراتي'), ('KWD', 'الدينار الكويتي'), ('QAR', 'الريال القطري'), ('BHD', 'الدينار البحريني'), ('OMR', 'الريال العماني'), ('EGP', 'الجنيه المصري'), ('LBP', 'الليرة اللبنانية'), ('SYP', 'الليرة السورية'), ('IQD', 'الدينار العراقي'), ('LYD', 'الدينار الليبي'), ('TND', 'الدينار التونسي'), ('DZD', 'الدينار الجزائري'), ('MAD', 'الدرهم المغربي'), ('SDG', 'الجنيه السوداني'), ('YER', 'الريال اليمني'), ('JPY', 'الين الياباني'), ('CHF', 'الفرنك السويسري'), ('CAD', 'الدولار الكندي'), ('AUD', 'الدولار الأسترالي'), ('CNY', 'اليوان الصيني'), ('INR', 'الروبية الهندية'), ('TRY', 'الليرة التركية'), ('IRR', 'الريال الإيراني'), ('PKR', 'الروبية الباكستانية'), ('AFN', 'الأفغاني')], max_length=3, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العملة')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='رمز العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='سعر الصرف مقابل العملة الأساسية', max_digits=10, verbose_name='سعر الصرف')),
                ('is_base_currency', models.BooleanField(default=False, help_text='العملة الأساسية للنظام', verbose_name='عملة أساسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('decimal_places', models.PositiveIntegerField(default=2, verbose_name='عدد الخانات العشرية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('company_name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة بالإنجليزية')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('logo', models.ImageField(blank=True, upload_to='company/', verbose_name='الشعار')),
                ('show_currency_symbol', models.BooleanField(default=True, verbose_name='إظهار رمز العملة')),
                ('date_format', models.CharField(default='Y-m-d', max_length=20, verbose_name='تنسيق التاريخ')),
                ('time_format', models.CharField(default='H:i', max_length=20, verbose_name='تنسيق الوقت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('base_currency', models.ForeignKey(help_text='العملة الأساسية للنظام', on_delete=django.db.models.deletion.PROTECT, to='settings.currency', verbose_name='العملة الأساسية')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
    ]
