# Generated by Django 4.2.7 on 2025-08-03 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_companysettings_enable_session_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='شعار الشركة الذي يظهر في المستندات المطبوعة', upload_to='company/', verbose_name='شعار الشركة للطباعة'),
        ),
        migrations.CreateModel(
            name='SuperadminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_logo', models.ImageField(blank=True, help_text='الشعار الذي يظهر في واجهة النظام', upload_to='system/', verbose_name='شعار النظام')),
                ('background_image', models.ImageField(blank=True, help_text='صورة خلفية النظام', upload_to='system/', verbose_name='صورة الخلفية')),
                ('background_opacity', models.DecimalField(decimal_places=2, default=0.8, help_text='مستوى شفافية صورة الخلفية (0.1 - 1.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='شفافية الخلفية')),
                ('primary_color', models.CharField(default='#007bff', help_text='اللون الأساسي للنظام (Hex Code)', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#6c757d', help_text='اللون الثانوي للنظام (Hex Code)', max_length=7, verbose_name='اللون الثانوي')),
                ('accent_color', models.CharField(default='#28a745', help_text='لون التمييز للنظام (Hex Code)', max_length=7, verbose_name='لون التمييز')),
                ('system_title', models.CharField(default='نظام إدارة الأعمال', help_text='العنوان الذي يظهر في النظام', max_length=100, verbose_name='عنوان النظام')),
                ('system_subtitle', models.CharField(blank=True, help_text='العنوان الفرعي للنظام', max_length=200, verbose_name='العنوان الفرعي')),
                ('show_company_info', models.BooleanField(default=True, help_text='إظهار معلومات الشركة في الواجهة', verbose_name='إظهار معلومات الشركة')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحديث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات السوبر أدمين',
                'verbose_name_plural': 'إعدادات السوبر أدمين',
                'db_table': 'superadmin_settings',
            },
        ),
    ]
