# Generated by Django 4.2.7 on 2025-08-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_alter_companysettings_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='مثال: invoice, receipt, purchase_order', max_length=100, unique=True, verbose_name='نوع المستند')),
                ('document_name_ar', models.CharField(max_length=200, verbose_name='اسم المستند بالعربية')),
                ('document_name_en', models.CharField(max_length=200, verbose_name='اسم المستند بالإنجليزية')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=2, verbose_name='حجم الورقة')),
                ('header_left_content', models.TextField(blank=True, null=True, verbose_name='محتوى يسار الرأس')),
                ('header_center_content', models.TextField(blank=True, null=True, verbose_name='محتوى وسط الرأس')),
                ('header_right_content', models.TextField(blank=True, null=True, verbose_name='محتوى يمين الرأس')),
                ('logo_position', models.CharField(choices=[('left', 'يسار'), ('center', 'وسط'), ('right', 'يمين')], default='center', max_length=10, verbose_name='موقع الشعار')),
                ('show_logo', models.BooleanField(default=True, verbose_name='إظهار الشعار')),
                ('footer_left_content', models.TextField(blank=True, null=True, verbose_name='محتوى يسار التذييل')),
                ('footer_center_content', models.TextField(blank=True, null=True, verbose_name='محتوى وسط التذييل')),
                ('footer_right_content', models.TextField(blank=True, null=True, verbose_name='محتوى يمين التذييل')),
                ('show_company_info', models.BooleanField(default=True, verbose_name='إظهار معلومات الشركة')),
                ('show_date_time', models.BooleanField(default=True, verbose_name='إظهار التاريخ والوقت')),
                ('show_page_numbers', models.BooleanField(default=True, verbose_name='إظهار أرقام الصفحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_settings', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_print_settings', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات طباعة المستند',
                'verbose_name_plural': 'إعدادات طباعة المستندات',
                'ordering': ['document_name_ar'],
            },
        ),
    ]
