# Generated by Django 4.2.7 on 2025-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_change_a3_to_a5_paper_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprintsettings',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], default='A4', max_length=2, verbose_name='حجم الورقة'),
        ),
    ]
