# Generated by Django 4.2.7 on 2025-08-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_documentprintsettings_paper_size'),
    ]

    operations = [
        # Migration فارغ - الحقول موجودة بالفعل في قاعدة البيانات
        # is_default, margins, orientation موجودة في الجدول
    ]
