# Generated by Django 4.2.7 on 2025-08-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_empty_migration'),
    ]

    operations = [
        # إضافة الأعمدة بشكل شرطي لتفادي الخطأ إذا كانت موجودة محلياً،
        # وفي نفس الوقت ضمان إضافتها على الإنتاج حيث هي مفقودة.
        migrations.RunSQL(
            sql=(
                """
                -- is_default
                ALTER TABLE settings_documentprintsettings
                ADD COLUMN IF NOT EXISTS is_default boolean;
                UPDATE settings_documentprintsettings SET is_default = FALSE WHERE is_default IS NULL;
                ALTER TABLE settings_documentprintsettings ALTER COLUMN is_default SET DEFAULT FALSE;
                ALTER TABLE settings_documentprintsettings ALTER COLUMN is_default SET NOT NULL;

                -- margins
                ALTER TABLE settings_documentprintsettings
                ADD COLUMN IF NOT EXISTS margins integer;
                UPDATE settings_documentprintsettings SET margins = 20 WHERE margins IS NULL;
                ALTER TABLE settings_documentprintsettings ALTER COLUMN margins SET DEFAULT 20;
                ALTER TABLE settings_documentprintsettings ALTER COLUMN margins SET NOT NULL;

                -- orientation
                ALTER TABLE settings_documentprintsettings
                ADD COLUMN IF NOT EXISTS orientation varchar(10);
                UPDATE settings_documentprintsettings SET orientation = 'portrait' WHERE orientation IS NULL;
                ALTER TABLE settings_documentprintsettings ALTER COLUMN orientation SET DEFAULT 'portrait';
                ALTER TABLE settings_documentprintsettings ALTER COLUMN orientation SET NOT NULL;
                """
            ),
            reverse_sql=(
                """
                ALTER TABLE settings_documentprintsettings DROP COLUMN IF EXISTS orientation;
                ALTER TABLE settings_documentprintsettings DROP COLUMN IF EXISTS margins;
                ALTER TABLE settings_documentprintsettings DROP COLUMN IF EXISTS is_default;
                """
            ),
        ),
    ]
