# Generated by Django 4.2.7 on 2025-08-25 09:58

from django.db import migrations

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_empty_migration'),
    ]

    operations = [
        migrations.RunPython(do_nothing, do_nothing),
    ]