# Generated by Django 4.2.7 on 2025-08-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_documentprintsettings_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprintsettings',
            name='is_default',
            field=models.BooleanField(default=False, help_text='هل هذا هو التصميم الافتراضي لهذا النوع من المستندات', verbose_name='افتراضي'),
        ),
        migrations.AddField(
            model_name='documentprintsettings',
            name='margins',
            field=models.IntegerField(default=20, help_text='هوامش الصفحة بالبكسل (قيمة موحدة لجميع الجهات)', verbose_name='الهوامش'),
        ),
        migrations.AddField(
            model_name='documentprintsettings',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'عمودي'), ('landscape', 'أفقي')], default='portrait', max_length=10, verbose_name='اتجاه الورقة'),
        ),
    ]
