# Generated by Django 4.2.7 on 2025-08-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_documentprintsettings_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoFotaraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='رابط API لنظام JoFotara', verbose_name='API URL')),
                ('client_id', models.CharField(help_text='معرف العميل', max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(help_text='سر العميل', max_length=255, verbose_name='Client Secret')),
                ('is_active', models.BooleanField(default=False, help_text='تفعيل الربط مع JoFotara', verbose_name='نشط')),
                ('use_mock_api', models.BooleanField(default=True, help_text='استخدام API وهمي للاختبار', verbose_name='استخدام Mock API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات JoFotara',
                'verbose_name_plural': 'إعدادات JoFotara',
            },
        ),
    ]
