# Generated by Django 4.2.7 on 2025-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_jofotarasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPermissionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Settings Permission Manager',
                'verbose_name_plural': 'Settings Permission Managers',
                'permissions': [('can_access_print_design', 'Can access print design settings')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
