# Generated by Django 4.2.7 on 2025-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_settingspermissionmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jofotarasettings',
            name='api_url',
            field=models.URLField(blank=True, help_text='رابط API لنظام JoFotara', null=True, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='jofotarasettings',
            name='client_id',
            field=models.CharField(blank=True, help_text='معرف العميل', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='jofotarasettings',
            name='client_secret',
            field=models.CharField(blank=True, help_text='سر العميل', max_length=255, verbose_name='Client Secret'),
        ),
    ]
