# Generated by Django 4.2.7 on 2025-09-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_jofotarasettings_api_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='base_currency',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='currency',
            field=models.CharField(default='JOD', help_text='رمز العملة الأساسية للنظام (مثل JOD, USD)', max_length=3, verbose_name='العملة الأساسية'),
        ),
    ]
