# Generated by Django 4.2.7 on 2025-09-29 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_remove_companysettings_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='base_currency',
            field=models.ForeignKey(blank=True, help_text='العملة الأساسية للنظام', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='العملة الأساسية'),
        ),
    ]
