# Generated by Django 4.2.7 on 2025-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_companysettings_base_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logout_on_browser_close',
            field=models.BooleanField(default=False, help_text='إنهاء الجلسة تلقائياً عند إغلاق المتصفح', verbose_name='تسجيل الخروج عند إغلاق المتصفح'),
        ),
    ]
