# Generated by Django 4.2.7 on 2025-12-11 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_disable_logout_on_browser_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='jofotarasettings',
            name='auto_transfer_enabled',
            field=models.BooleanField(default=False, help_text='تفعيل ترحيل المستندات تلقائياً', verbose_name='تفعيل الترحيل التلقائي'),
        ),
        migrations.AddField(
            model_name='jofotarasettings',
            name='immediate_transfer',
            field=models.BooleanField(default=False, help_text='ترحيل المستندات فور إنشائها', verbose_name='الترحيل الفوري'),
        ),
        migrations.AddField(
            model_name='jofotarasettings',
            name='transfer_day_of_month',
            field=models.PositiveIntegerField(blank=True, help_text='يوم محدد من الشهر لترحيل المستندات (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='يوم الترحيل من الشهر'),
        ),
        migrations.AddField(
            model_name='jofotarasettings',
            name='transfer_time',
            field=models.TimeField(blank=True, help_text='الساعة اليومية لترحيل المستندات تلقائياً', null=True, verbose_name='وقت الترحيل التلقائي'),
        ),
    ]
