# Generated by Django 4.2.7 on 2025-09-26 11:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0008_yearendclosing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_type', models.CharField(choices=[('bad_debt', 'مخصص الديون المشكوك في تحصيلها'), ('depreciation', 'مخصص الاهلاك'), ('inventory', 'مخصص المخزون'), ('warranty', 'مخصص الضمان'), ('tax', 'مخصص الضرائب'), ('other', 'مخصصات أخرى')], max_length=20, verbose_name='نوع المخصص')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المخصص')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='المبلغ')),
                ('accumulated_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ المتراكم')),
                ('fiscal_year', models.IntegerField(verbose_name='السنة المالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_provisions', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'مخصص',
                'verbose_name_plural': 'المخصصات',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'نوع المخصص',
                'verbose_name_plural': 'أنواع المخصصات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journalentry', verbose_name='القيد المحاسبي')),
                ('provision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisions.provision', verbose_name='المخصص')),
            ],
            options={
                'verbose_name': 'قيد مخصص',
                'verbose_name_plural': 'قيود المخصصات',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='provision',
            name='custom_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisions.provisiontype', verbose_name='نوع مخصص مخصص'),
        ),
        migrations.AddField(
            model_name='provision',
            name='provision_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='journal.account', verbose_name='حساب المخصص'),
        ),
        migrations.AddField(
            model_name='provision',
            name='related_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.account', verbose_name='الحساب المرتبط'),
        ),
        migrations.AlterUniqueTogether(
            name='provision',
            unique_together={('provision_type', 'related_account', 'fiscal_year')},
        ),
    ]
