# Generated by Django 4.2.7 on 2025-11-30 09:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_update_fiscal_year_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provision',
            options={'ordering': ['-fiscal_year', '-created_at'], 'verbose_name': 'Provision', 'verbose_name_plural': 'Provisions'},
        ),
        migrations.AlterModelOptions(
            name='provisionentry',
            options={'ordering': ['-date'], 'verbose_name': 'Provision Entry', 'verbose_name_plural': 'Provision Entries'},
        ),
        migrations.AlterModelOptions(
            name='provisiontype',
            options={'ordering': ['name'], 'verbose_name': 'Provision Type', 'verbose_name_plural': 'Provision Types'},
        ),
        migrations.AlterField(
            model_name='provision',
            name='accumulated_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Accumulated Amount'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_provisions', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='custom_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisions.provisiontype', verbose_name='Custom Provision Type'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='fiscal_year',
            field=models.IntegerField(verbose_name='Fiscal Year'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Provision Name'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='provision_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='journal.account', verbose_name='Provision Account'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='provision_type',
            field=models.CharField(choices=[('bad_debt', 'Bad Debt Provision'), ('depreciation', 'Depreciation Provision'), ('inventory', 'Inventory Provision'), ('warranty', 'Warranty Provision'), ('tax', 'Tax Provision'), ('other', 'Other Provisions')], max_length=20, verbose_name='Provision Type'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='related_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.account', verbose_name='Related Account'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='provisionentry',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='provisionentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AlterField(
            model_name='provisionentry',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisions.provision', verbose_name='Provision'),
        ),
        migrations.AlterField(
            model_name='provisiontype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Type Name'),
        ),
    ]
