# Generated by Django 4.2.7 on 2025-07-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحركة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('movement_type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر'), ('transfer', 'تحويل'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('reference_type', models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مردود مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مردود مشتريات'), ('warehouse_transfer', 'تحويل مستودع'), ('adjustment', 'تسوية')], max_length=30, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveIntegerField(verbose_name='معرف المرجع')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-date', '-movement_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستودع')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المستودع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تحويل مستودع',
                'verbose_name_plural': 'تحويلات المستودعات',
                'ordering': ['-date', '-transfer_number'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='التكلفة الإجمالية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousetransfer', verbose_name='التحويل')),
            ],
            options={
                'verbose_name': 'عنصر تحويل المستودع',
                'verbose_name_plural': 'عناصر تحويل المستودعات',
            },
        ),
    ]
