# Generated by Django 4.2.7 on 2025-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorymovement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مردود مبيعات'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مردود مشتريات'), ('warehouse_transfer', 'تحويل مستودع'), ('adjustment', 'تسوية'), ('opening_balance', 'رصيد افتتاحي')], max_length=30, verbose_name='نوع المرجع'),
        ),
    ]
