# Generated by Django 4.2.7 on 2025-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='المستودع الافتراضي'),
        ),
    ]
