# Generated by Django 4.2.7 on 2025-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_warehouse_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'وارد'), ('out', 'صادر'), ('transfer', 'تحويل'), ('adjustment', 'settlement')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('sales_return', 'Sales Return'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_return', 'Purchase Return'), ('warehouse_transfer', 'Warehouse Transfer'), ('adjustment', 'Adjustment'), ('opening_balance', 'Opening Balance')], max_length=30, verbose_name='نوع المرجع'),
        ),
    ]
