# Generated by Django 4.2.7 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorymovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Movement Number'),
        ),
    ]
