# Generated by Django 4.2.7 on 2025-09-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorymovement_movement_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-date', '-movement_number'], 'permissions': [('can_view_inventory', 'Can access inventory')], 'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'permissions': [('can_view_inventory', 'Can access inventory')], 'verbose_name': 'مستودع', 'verbose_name_plural': 'المستودعات'},
        ),
    ]
