# Generated by Django 4.2.7 on 2025-10-19 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_alter_inventorymovement_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-date', '-movement_number'], 'permissions': [('can_view_inventory', 'Can access inventory')], 'verbose_name': 'Inventory Movement', 'verbose_name_plural': 'Inventory Movements'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'permissions': [('can_view_inventory', 'Can access inventory')], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehousetransfer',
            options={'ordering': ['-date', '-transfer_number'], 'verbose_name': 'Warehouse Transfer', 'verbose_name_plural': 'Warehouse Transfers'},
        ),
        migrations.AlterModelOptions(
            name='warehousetransferitem',
            options={'verbose_name': 'Warehouse Transfer Item', 'verbose_name_plural': 'Warehouse Transfer Items'},
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('transfer', 'Transfer'), ('adjustment', 'settlement')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_id',
            field=models.PositiveIntegerField(verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('sales_return', 'Sales Return'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_return', 'Purchase Return'), ('warehouse_transfer', 'Warehouse Transfer'), ('adjustment', 'Adjustment'), ('opening_balance', 'Opening Balance')], max_length=30, verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Warehouse Code'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Manager'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Warehouse Name'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_warehouses', to='inventory.warehouse', verbose_name='Parent Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='inventory.warehouse', verbose_name='From Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='inventory.warehouse', verbose_name='To Warehouse'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousetransfer', verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='warehousetransferitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Unit Cost'),
        ),
    ]
