# Generated by Django 4.2.7 on 2025-11-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorymovement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'default_permissions': [], 'ordering': ['-date', '-movement_number'], 'verbose_name': 'Inventory Movement', 'verbose_name_plural': 'Inventory Movements'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'permissions': [('can_view_inventory', 'Can access inventory'), ('can_add_inventory', 'Can add inventory'), ('can_edit_inventory', 'Can edit inventory'), ('can_delete_inventory', 'Can delete inventory')], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehousetransfer',
            options={'default_permissions': [], 'ordering': ['-date', '-transfer_number'], 'verbose_name': 'Warehouse Transfer', 'verbose_name_plural': 'Warehouse Transfers'},
        ),
        migrations.AlterModelOptions(
            name='warehousetransferitem',
            options={'default_permissions': [], 'verbose_name': 'Warehouse Transfer Item', 'verbose_name_plural': 'Warehouse Transfer Items'},
        ),
    ]
