# Generated by Django 4.2.7 on 2025-11-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventorymovement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_inventory', 'Can access inventory'), ('can_add_inventory', 'Can add inventory'), ('can_edit_inventory', 'Can edit inventory'), ('can_delete_inventory', 'Can delete inventory')], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
