# Generated by Django 4.2.7 on 2025-11-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_disable_default_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_inventory_stock', 'Can View Inventory Stock'), ('can_view_warehouses', 'Can View Warehouses'), ('can_add_warehouses', 'Can Add Warehouses'), ('can_edit_warehouses', 'Can Edit Warehouses'), ('can_delete_warehouses', 'Can Delete Warehouses'), ('can_view_inventory_movements', 'Can View Inventory Movements'), ('can_add_inventory_movements', 'Can Add Inventory Movements'), ('can_edit_inventory_movements', 'Can Edit Inventory Movements'), ('can_delete_inventory_movements', 'Can Delete Inventory Movements'), ('can_view_warehouse_transfers', 'Can View Warehouse Transfers'), ('can_add_warehouse_transfers', 'Can Add Warehouse Transfers'), ('can_edit_warehouse_transfers', 'Can Edit Warehouse Transfers'), ('can_delete_warehouse_transfers', 'Can Delete Warehouse Transfers'), ('can_view_stock_alerts', 'Can View Stock Alerts')], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
