# Generated by Django 4.2.7 on 2025-08-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'تحكم وصول التقارير',
                'verbose_name_plural': 'تحكم وصول التقارير',
                'permissions': [('can_view_customer_statement', 'عرض كشف حساب العملاء')],
            },
        ),
    ]
