# Generated by Django 4.2.7 on 2025-11-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportaccesscontrol',
            options={'permissions': [('can_view_customer_statement', 'View Customer Statement')], 'verbose_name': 'Report Access Control', 'verbose_name_plural': 'Report Access Controls'},
        ),
    ]
