# Generated by Django 4.2.7 on 2025-11-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportaccesscontrol_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportaccesscontrol',
            options={'default_permissions': [], 'permissions': [('can_view_sales_reports', 'Can View Sales Reports'), ('can_view_sales_by_representative_report', 'Can View Sales By Representative Report'), ('can_view_purchase_reports', 'Can View Purchase Reports'), ('can_view_tax_report', 'Can View Tax Report'), ('can_view_profit_loss_report', 'Can View Profit and Loss Report'), ('can_view_customer_statement', 'Can View Customer Statement'), ('can_view_trial_balance', 'Can View Trial Balance'), ('can_view_balance_sheet', 'Can View Balance Sheet'), ('can_view_income_statement', 'Can View Income Statement'), ('can_view_cash_flow_statement', 'Can View Cash Flow Statement'), ('can_view_aging_report', 'Can View Aging Report'), ('can_view_stock_balance_report', 'Can View Stock Balance Report'), ('can_view_financial_ratios', 'Can View Financial Ratios'), ('can_view_documents_report', 'Can View Documents Report')], 'verbose_name': 'Report Access Control', 'verbose_name_plural': 'Report Access Controls'},
        ),
    ]
