# Generated by Django 4.2.7 on 2025-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('both', 'عميل ومورد')], max_length=20, verbose_name='النوع')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('credit_limit', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='حد الائتمان')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل/مورد',
                'verbose_name_plural': 'العملاء والموردون',
                'ordering': ['name'],
            },
        ),
    ]
