# Generated by Django 4.2.7 on 2025-07-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupplier',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='المدينة'),
            preserve_default=False,
        ),
    ]
