# Generated by Django 4.2.7 on 2025-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customersupplier_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'ordering': ['sequence_number'], 'verbose_name': 'عميل/مورد', 'verbose_name_plural': 'العملاء والموردون'},
        ),
        migrations.AddField(
            model_name='customersupplier',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='الرقم التسلسلي'),
        ),
    ]
