# Generated by Django 4.2.7 on 2025-09-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_deletion_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'ordering': ['sequence_number'], 'permissions': [('can_view_customers_suppliers', 'يمكن مشاهدة العملاء/الموردين'), ('can_add_customers_suppliers', 'يمكن إضافة عميل/مورد'), ('can_edit_customers_suppliers', 'يمكن تعديل عميل/مورد'), ('can_delete_customers_suppliers', 'يمكن حذف عميل/مورد')], 'verbose_name': 'عميل/مورد', 'verbose_name_plural': 'العملاء والموردون'},
        ),
    ]
