# Generated by Django 4.2.7 on 2025-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customersupplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'ordering': ['sequence_number'], 'permissions': [('can_view_customers_suppliers', 'Can view customers/suppliers'), ('can_add_customers_suppliers', 'Can add customer/supplier'), ('can_edit_customers_suppliers', 'Can edit customer/supplier'), ('can_delete_customers_suppliers', 'Can delete customer/supplier')], 'verbose_name': 'Customer/Supplier', 'verbose_name_plural': 'Customers and Suppliers'},
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Sequence Number'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='customersupplier',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer and Supplier')], max_length=20, verbose_name='Type'),
        ),
    ]
