# Generated by Django 4.2.7 on 2025-11-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customersupplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'default_permissions': [], 'ordering': ['sequence_number'], 'permissions': [('can_view_customers_suppliers', 'Can View Customers and Suppliers'), ('can_add_customers_suppliers', 'Can Add Customers and Suppliers'), ('can_edit_customers_suppliers', 'Can Edit Customers and Suppliers'), ('can_delete_customers_suppliers', 'Can Delete Customers and Suppliers')], 'verbose_name': 'Customer/Supplier', 'verbose_name_plural': 'Customers and Suppliers'},
        ),
    ]
