# Generated by Django 4.2.7 on 2025-11-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customersupplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'default_permissions': [], 'ordering': ['sequence_number'], 'permissions': [('can_view_customers', 'Can View Customers'), ('can_add_customers', 'Can Add Customers'), ('can_edit_customers', 'Can Edit Customers'), ('can_delete_customers', 'Can Delete Customers')], 'verbose_name': 'Customer/Supplier', 'verbose_name_plural': 'Customers and Suppliers'},
        ),
    ]
