# Generated by Django 4.2.7 on 2025-11-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_update_customer_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersupplier',
            options={'default_permissions': [], 'ordering': ['sequence_number'], 'permissions': [('can_view_customers', 'Can View Customers'), ('can_add_customers', 'Can Add Customers'), ('can_edit_customers', 'Can Edit Customers'), ('can_delete_customers', 'Can Delete Customers'), ('can_view_suppliers', 'Can View Suppliers'), ('can_add_suppliers', 'Can Add Suppliers'), ('can_edit_suppliers', 'Can Edit Suppliers'), ('can_delete_suppliers', 'Can Delete Suppliers')], 'verbose_name': 'Customer/Supplier', 'verbose_name_plural': 'Customers and Suppliers'},
        ),
    ]
