# Generated by Django 4.2.7 on 2025-07-11 12:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('type', models.CharField(choices=[('revenue', 'إيراد'), ('expense', 'مصروف')], max_length=20, verbose_name='نوع الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'فئة الإيرادات والمصروفات',
                'verbose_name_plural': 'فئات الإيرادات والمصروفات',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RevenueExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('type', models.CharField(choices=[('revenue', 'إيراد'), ('expense', 'مصروف')], max_length=20, verbose_name='نوع القيد')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنكي'), ('cheque', 'شيك'), ('transfer', 'تحويل')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_revenue_expenses', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues_expenses.revenueexpensecategory', verbose_name='الفئة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قيد الإيرادات والمصروفات',
                'verbose_name_plural': 'قيود الإيرادات والمصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRevenueExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الإيراد/المصروف المتكرر')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='المبلغ')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('last_generated', models.DateField(blank=True, null=True, verbose_name='آخر تاريخ توليد')),
                ('next_due_date', models.DateField(verbose_name='التاريخ المستحق التالي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنكي'), ('cheque', 'شيك'), ('transfer', 'تحويل')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_generate', models.BooleanField(default=True, verbose_name='توليد تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues_expenses.revenueexpensecategory', verbose_name='الفئة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'الإيراد/المصروف المتكرر',
                'verbose_name_plural': 'الإيرادات والمصروفات المتكررة',
                'ordering': ['next_due_date'],
            },
        ),
    ]
