# Generated by Django 4.2.7 on 2025-09-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues_expenses', '0003_alter_recurringrevenueexpense_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringrevenueexpense',
            options={'ordering': ['next_due_date'], 'verbose_name': 'الإيراد/المصروف المتكرر', 'verbose_name_plural': 'Recurring revenues and expenses'},
        ),
    ]
