# Generated by Django 4.2.7 on 2025-10-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_journalentry_reference_type'),
        ('revenues_expenses', '0005_sector_recurringrevenueexpense_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueexpensecategory',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['revenue', 'expense']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.account', verbose_name='الحساب المحاسبي'),
        ),
    ]
