# Generated by Django 4.2.7 on 2025-11-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues_expenses', '0006_revenueexpensecategory_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenueexpensecategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'permissions': [('can_view_categories', 'View Revenue/Expense Categories'), ('can_add_categories', 'Add Revenue/Expense Categories'), ('can_edit_categories', 'Edit Revenue/Expense Categories'), ('can_delete_categories', 'Delete Revenue/Expense Categories')], 'verbose_name': 'فئة الإيرادات والمصروفات', 'verbose_name_plural': 'فئات الإيرادات والمصروفات'},
        ),
        migrations.AlterModelOptions(
            name='revenueexpenseentry',
            options={'default_permissions': [], 'ordering': ['-date', '-created_at'], 'permissions': [('can_view_entries', 'View Revenue/Expense Entries'), ('can_add_entries', 'Add Revenue/Expense Entries'), ('can_edit_entries', 'Edit Revenue/Expense Entries'), ('can_delete_entries', 'Delete Revenue/Expense Entries')], 'verbose_name': 'قيد الإيرادات والمصروفات', 'verbose_name_plural': 'قيود الإيرادات والمصروفات'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_sectors', 'View Sectors'), ('can_add_sectors', 'Add Sectors'), ('can_edit_sectors', 'Edit Sectors'), ('can_delete_sectors', 'Delete Sectors')], 'verbose_name': 'قطاع', 'verbose_name_plural': 'القطاعات'},
        ),
    ]
