# Generated by Django 4.2.7 on 2025-11-16 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0025_alter_account_options_alter_fiscalyear_options_and_more'),
        ('revenues_expenses', '0007_alter_revenueexpensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringrevenueexpense',
            options={'default_permissions': [], 'ordering': ['next_due_date'], 'verbose_name': 'Recurring Revenue/Expense', 'verbose_name_plural': 'Recurring revenues and expenses'},
        ),
        migrations.AlterModelOptions(
            name='revenueexpensecategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'permissions': [('can_view_categories', 'View Revenue/Expense Categories'), ('can_add_categories', 'Add Revenue/Expense Categories'), ('can_edit_categories', 'Edit Revenue/Expense Categories'), ('can_delete_categories', 'Delete Revenue/Expense Categories')], 'verbose_name': 'Revenue/Expense Category', 'verbose_name_plural': 'Revenue/Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='revenueexpenseentry',
            options={'default_permissions': [], 'ordering': ['-date', '-created_at'], 'permissions': [('can_view_entries', 'View Revenue/Expense Entries'), ('can_add_entries', 'Add Revenue/Expense Entries'), ('can_edit_entries', 'Edit Revenue/Expense Entries'), ('can_delete_entries', 'Delete Revenue/Expense Entries')], 'verbose_name': 'Revenue/Expense Entry', 'verbose_name_plural': 'Revenue/Expense Entries'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('can_view_sectors', 'View Sectors'), ('can_add_sectors', 'Add Sectors'), ('can_edit_sectors', 'Edit Sectors'), ('can_delete_sectors', 'Delete Sectors')], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='auto_generate',
            field=models.BooleanField(default=True, verbose_name='Auto Generate'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues_expenses.revenueexpensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='last_generated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Generation Date'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Recurring Revenue/Expense Name'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='next_due_date',
            field=models.DateField(verbose_name='Next Due Date'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('transfer', 'Transfer')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenues_expenses.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='recurringrevenueexpense',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='revenueexpensecategory',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['revenue', 'expense']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.account', verbose_name='Accounting Account'),
        ),
        migrations.AlterField(
            model_name='revenueexpensecategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='revenueexpensecategory',
            name='type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20, verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_revenue_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues_expenses.revenueexpensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='entry_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('transfer', 'Transfer')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenues_expenses.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='revenueexpenseentry',
            name='type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sector Name'),
        ),
    ]
