# Generated by Django 4.2.7 on 2025-11-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues_expenses', '0008_alter_recurringrevenueexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringrevenueexpense',
            options={'default_permissions': [], 'ordering': ['next_due_date'], 'permissions': [('can_view_recurring', 'View Recurring Revenue/Expense'), ('can_add_recurring', 'Add Recurring Revenue/Expense'), ('can_edit_recurring', 'Edit Recurring Revenue/Expense'), ('can_delete_recurring', 'Delete Recurring Revenue/Expense')], 'verbose_name': 'Recurring Revenue/Expense', 'verbose_name_plural': 'Recurring revenues and expenses'},
        ),
    ]
