# Generated by Django 4.2.7 on 2025-11-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues_expenses', '0009_alter_recurringrevenueexpense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringrevenueexpense',
            options={'default_permissions': [], 'ordering': ['next_due_date'], 'verbose_name': 'Recurring Revenue/Expense', 'verbose_name_plural': 'Recurring revenues and expenses'},
        ),
        migrations.AlterModelOptions(
            name='revenueexpensecategory',
            options={'default_permissions': [], 'ordering': ['type', 'name'], 'verbose_name': 'Revenue/Expense Category', 'verbose_name_plural': 'Revenue/Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='revenueexpenseentry',
            options={'default_permissions': [], 'ordering': ['-date', '-created_at'], 'permissions': [('can_view_revenues_expenses', 'Can View Revenues/Expenses'), ('can_add_revenues_expenses', 'Can Add Revenues/Expenses'), ('can_edit_revenues_expenses', 'Can Edit Revenues/Expenses'), ('can_delete_revenues_expenses', 'Can Delete Revenues/Expenses')], 'verbose_name': 'Revenue/Expense Entry', 'verbose_name_plural': 'Revenue/Expense Entries'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'default_permissions': [], 'ordering': ['name'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
    ]
