# Generated by Django 4.2.7 on 2025-09-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Backup Manager',
                'verbose_name_plural': 'Backup Managers',
                'permissions': [('can_delete_advanced_data', 'Can delete advanced data tables'), ('delete_backup', 'Can delete backup files')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
