# Generated by Django 4.2.7 on 2025-09-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupmanager',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_restore_backup', 'Can restore backup'), ('can_delete_advanced_data', 'Can delete advanced data tables'), ('delete_backup', 'Can delete backup files')], 'verbose_name': 'Backup Manager', 'verbose_name_plural': 'Backup Managers'},
        ),
    ]
