# Generated by Django 4.2.7 on 2025-07-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('payment_type', models.CharField(choices=[('cash', 'كاش'), ('credit', 'ذمم')], max_length=20, verbose_name='نوع الدفع')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المجموع الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الخصم')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فاتورة مبيعات',
                'verbose_name_plural': 'فواتير المبيعات',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='سعر الوحدة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة المبيعات',
                'verbose_name_plural': 'عناصر فواتير المبيعات',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المردود')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المجموع الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مردود مبيعات',
                'verbose_name_plural': 'مردود المبيعات',
                'ordering': ['-date', '-return_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='سعر الوحدة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='المنتج')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn', verbose_name='مردود المبيعات')),
            ],
            options={
                'verbose_name': 'عنصر مردود المبيعات',
                'verbose_name_plural': 'عناصر مردود المبيعات',
            },
        ),
    ]
