# Generated by Django 4.2.7 on 2025-07-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__in': ['customer', 'both']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='العميل'),
        ),
    ]
