# Generated by Django 4.2.7 on 2025-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesinvoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'ذمم (آجل)'), ('bank_transfer', 'تحويل بنكي'), ('check', 'شيك'), ('installment', 'تقسيط')], max_length=20, verbose_name='نوع الدفع'),
        ),
    ]
