# Generated by Django 4.2.7 on 2025-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesinvoice_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='return_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم مرتجع المبيعات'),
        ),
    ]
