# Generated by Django 4.2.7 on 2025-08-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0004_cashboxtransfer_check_bank_name_and_more'),
        ('sales', '0005_alter_salesreturn_return_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cashbox',
            field=models.ForeignKey(blank=True, help_text='الصندوق المحصل منه النقد للمبيعات النقدية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashboxes.cashbox', verbose_name='الصندوق'),
        ),
    ]
