# Generated by Django 4.2.7 on 2025-08-28 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0004_alter_customersupplier_options_and_more'),
        ('sales', '0008_add_inclusive_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': (('can_toggle_invoice_tax', 'Can toggle invoice tax inclusion'), ('can_change_invoice_creator', 'Can change invoice creator')), 'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(max_length=50, unique=True, verbose_name='رقم إشعار دائن')),
                ('date', models.DateField(verbose_name='Date')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المجموع الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'اشعار دائن',
                'verbose_name_plural': 'اشعارات دائن',
                'ordering': ['-date', '-note_number'],
            },
        ),
    ]
