# Generated by Django 4.2.7 on 2025-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_salesinvoice_options_salescreditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='jofotara_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when invoice was sent to JoFotara', null=True, verbose_name='Sent to JoFotara At'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='jofotara_uuid',
            field=models.CharField(blank=True, help_text='UUID returned from JoFotara API', max_length=100, null=True, verbose_name='JoFotara UUID'),
        ),
    ]
