# Generated by Django 4.2.7 on 2025-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice_jofotara_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': (('can_toggle_invoice_tax', 'Can toggle invoice tax inclusion'), ('can_change_invoice_creator', 'Can change invoice creator'), ('can_send_to_jofotara', 'Can send invoices to JoFotara')), 'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='jofotara_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when credit note was sent to JoFotara', null=True, verbose_name='Sent to JoFotara At'),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='jofotara_uuid',
            field=models.CharField(blank=True, help_text='UUID returned from JoFotara API', max_length=100, null=True, verbose_name='JoFotara UUID'),
        ),
    ]
