# Generated by Django 4.2.7 on 2025-09-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_jofotara_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'ordering': ['-date', '-note_number'], 'permissions': (('can_send_to_jofotara', 'Can send credit notes to JoFotara'),), 'verbose_name': 'اشعار دائن', 'verbose_name_plural': 'اشعارات دائن'},
        ),
    ]
