# Generated by Django 4.2.7 on 2025-09-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_salescreditnote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': (('can_toggle_invoice_tax', 'Can toggle invoice tax inclusion'), ('can_change_invoice_creator', 'Can change invoice creator'), ('can_send_to_jofotara', 'Can send invoices to JoFotara')), 'verbose_name': 'Sales Invoice', 'verbose_name_plural': 'Sales Invoices'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-date', '-return_number'], 'verbose_name': 'Sales Return', 'verbose_name_plural': 'Sales Returns'},
        ),
    ]
