# Generated by Django 4.2.7 on 2025-09-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventorymovement_options_and_more'),
        ('sales', '0013_alter_salesinvoice_options_alter_salesreturn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المستودع'),
        ),
    ]
