# Generated by Django 4.2.7 on 2025-09-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_category_code_alter_category_name_en_and_more'),
        ('inventory', '0010_alter_inventorymovement_product_and_more'),
        ('customers', '0006_alter_customersupplier_options'),
        ('sales', '0014_salesinvoice_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescreditnote',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='salescreditnote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__in': ['customer', 'both']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customersupplier', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product'),
        ),
    ]
