# Generated by Django 4.2.7 on 2025-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_salesinvoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='jofotara_verification_url',
            field=models.URLField(blank=True, help_text='URL to verify invoice on JoFotara portal', null=True, verbose_name='JoFotara Verification URL'),
        ),
    ]
