# Generated by Django 4.2.7 on 2025-10-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_add_jofotara_verification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='jofotara_verification_url',
            field=models.URLField(blank=True, help_text='URL to verify credit note on JoFotara portal', null=True, verbose_name='JoFotara Verification URL'),
        ),
    ]
