# Generated by Django 4.2.7 on 2025-10-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_add_jofotara_verification_url_creditnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'ordering': ['-date', '-note_number'], 'permissions': (('can_view_creditnote', 'Can view اشعار دائن'), ('can_send_to_jofotara', 'Can send credit notes to JoFotara')), 'verbose_name': 'اشعار دائن', 'verbose_name_plural': 'اشعارات دائن'},
        ),
    ]
