# Generated by Django 4.2.7 on 2025-10-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0017_alter_cashboxtransaction_options_and_more'),
        ('sales', '0019_add_creditnote_view_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'ordering': ['-date', '-note_number'], 'permissions': (('can_view_creditnote', 'Can view Credit Note'), ('can_send_to_jofotara', 'Can send credit notes to JoFotara')), 'verbose_name': 'Credit Note', 'verbose_name_plural': 'Credit Notes'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceitem',
            options={'verbose_name': 'Sales Invoice Item', 'verbose_name_plural': 'Sales Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'verbose_name': 'Sales Return Item', 'verbose_name_plural': 'Sales Return Items'},
        ),
        migrations.AlterField(
            model_name='salescreditnote',
            name='note_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Credit Note Number'),
        ),
        migrations.AlterField(
            model_name='salescreditnote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='salescreditnote',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salescreditnote',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cashbox',
            field=models.ForeignKey(blank=True, help_text='Cashbox from which cash is collected for cash sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashboxes.cashbox', verbose_name='Cashbox'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='inclusive_tax',
            field=models.BooleanField(default=True, verbose_name='Inclusive Tax'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('installment', 'Installment')], max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesinvoice', verbose_name='Original Invoice'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sales Return Number'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='return_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn', verbose_name='Sales Return'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Unit Price'),
        ),
    ]
