# Generated by Django 4.2.7 on 2025-10-31 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_salescreditnote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoice', verbose_name='Original Invoice'),
        ),
    ]
