# Generated by Django 4.2.7 on 2025-11-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_change_return_foreign_key_to_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'default_permissions': [], 'ordering': ['-date', '-note_number'], 'verbose_name': 'Credit Note', 'verbose_name_plural': 'Credit Notes'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'default_permissions': [], 'ordering': ['-date', '-invoice_number'], 'permissions': [('can_view_sales', 'Can View Sales'), ('can_add_sales', 'Can Add Sales'), ('can_edit_sales', 'Can Edit Sales'), ('can_delete_sales', 'Can Delete Sales')], 'verbose_name': 'Sales Invoice', 'verbose_name_plural': 'Sales Invoices'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceitem',
            options={'default_permissions': [], 'verbose_name': 'Sales Invoice Item', 'verbose_name_plural': 'Sales Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'default_permissions': [], 'ordering': ['-date', '-return_number'], 'permissions': [('can_view_sales_returns', 'Can View Sales Returns'), ('can_add_sales_returns', 'Can Add Sales Returns'), ('can_edit_sales_returns', 'Can Edit Sales Returns'), ('can_delete_sales_returns', 'Can Delete Sales Returns')], 'verbose_name': 'Sales Return', 'verbose_name_plural': 'Sales Returns'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'default_permissions': [], 'verbose_name': 'Sales Return Item', 'verbose_name_plural': 'Sales Return Items'},
        ),
    ]
