# Generated by Django 4.2.7 on 2025-11-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_salescreditnote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'default_permissions': [], 'ordering': ['-date', '-note_number'], 'permissions': [('can_view_credit_notes', 'Can View Credit Notes'), ('can_add_credit_notes', 'Can Add Credit Notes'), ('can_edit_credit_notes', 'Can Edit Credit Notes'), ('can_delete_credit_notes', 'Can Delete Credit Notes')], 'verbose_name': 'Credit Note', 'verbose_name_plural': 'Credit Notes'},
        ),
    ]
