# Generated by Django 4.2.7 on 2025-11-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_update_creditnote_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={
                'default_permissions': [],
                'ordering': ['-date', '-invoice_number'],
                'permissions': [
                    ('can_view_sales', 'Can View Sales'),
                    ('can_add_sales', 'Can Add Sales'),
                    ('can_edit_sales', 'Can Edit Sales'),
                    ('can_delete_sales', 'Can Delete Sales'),
                    ('can_view_sales_statement', 'Can View Sales Statement'),
                    ('can_view_sales_returns_statement', 'Can View Sales Returns Statement'),
                    ('can_view_pos', 'Can View POS'),
                    ('can_access_pos', 'Can Access POS'),
                    ('can_edit_pos', 'Can Edit POS'),
                    ('can_delete_pos', 'Can Delete POS'),
                ],
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices'
            },
        ),
    ]
