# Generated by Django 4.2.7 on 2025-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_update_sales_statements_pos_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescreditnote',
            options={'default_permissions': [], 'ordering': ['-date', '-note_number'], 'permissions': [('can_view_credit_notes', 'Can View Credit Notes'), ('can_add_credit_notes', 'Can Add Credit Notes'), ('can_edit_credit_notes', 'Can Edit Credit Notes'), ('can_delete_credit_notes', 'Can Delete Credit Notes'), ('can_post_credit_notes', 'Can Post Credit Notes to Tax Authority')], 'verbose_name': 'Credit Note', 'verbose_name_plural': 'Credit Notes'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'default_permissions': [], 'ordering': ['-date', '-invoice_number'], 'permissions': [('can_view_sales', 'Can View Sales'), ('can_add_sales', 'Can Add Sales'), ('can_edit_sales', 'Can Edit Sales'), ('can_delete_sales', 'Can Delete Sales'), ('can_post_sales', 'Can Post Sales to Tax Authority'), ('can_view_sales_statement', 'Can View Sales Statement'), ('can_view_sales_returns_statement', 'Can View Sales Returns Statement'), ('can_view_pos', 'Can View POS'), ('can_access_pos', 'Can Access POS'), ('can_edit_pos', 'Can Edit POS'), ('can_delete_pos', 'Can Delete POS')], 'verbose_name': 'Sales Invoice', 'verbose_name_plural': 'Sales Invoices'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'default_permissions': [], 'ordering': ['-date', '-return_number'], 'permissions': [('can_view_sales_returns', 'Can View Sales Returns'), ('can_add_sales_returns', 'Can Add Sales Returns'), ('can_edit_sales_returns', 'Can Edit Sales Returns'), ('can_delete_sales_returns', 'Can Delete Sales Returns'), ('can_post_sales_returns', 'Can Post Sales Returns to Tax Authority')], 'verbose_name': 'Sales Return', 'verbose_name_plural': 'Sales Returns'},
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='is_posted_to_tax',
            field=models.BooleanField(default=False, help_text='Whether this credit note has been posted to Income and Sales Tax Department', verbose_name='Posted to Tax Authority'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_posted_to_tax',
            field=models.BooleanField(default=False, help_text='Whether this invoice has been posted to Income and Sales Tax Department', verbose_name='Posted to Tax Authority'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='is_posted_to_tax',
            field=models.BooleanField(default=False, help_text='Whether this return has been posted to Income and Sales Tax Department', verbose_name='Posted to Tax Authority'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='jofotara_sent_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when return was sent to JoFotara', null=True, verbose_name='Sent to JoFotara At'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='jofotara_uuid',
            field=models.CharField(blank=True, help_text='UUID returned from JoFotara API', max_length=100, null=True, verbose_name='JoFotara UUID'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='jofotara_verification_url',
            field=models.URLField(blank=True, help_text='URL to verify return on JoFotara portal', null=True, verbose_name='JoFotara Verification URL'),
        ),
    ]
