# Generated by Django 4.2.7 on 2025-11-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_salescreditnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='jofotara_qr_code',
            field=models.TextField(blank=True, help_text='QR Code image data from JoFotara (base64 or URL)', null=True, verbose_name='JoFotara QR Code'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='jofotara_qr_code',
            field=models.TextField(blank=True, help_text='QR Code image data from JoFotara (base64 or URL)', null=True, verbose_name='JoFotara QR Code'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='jofotara_qr_code',
            field=models.TextField(blank=True, help_text='QR Code image data from JoFotara (base64 or URL)', null=True, verbose_name='JoFotara QR Code'),
        ),
    ]
