# Generated by Django 4.2.7 on 2026-06-07 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0027_add_jofotara_qr_code_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='pos_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', help_text='POS payment method used for this invoice', max_length=20, verbose_name='POS Payment Method'),
        ),
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_pos_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Closed By')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_pos_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Opened By')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'pos_user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='POS User')),
            ],
            options={
                'verbose_name': 'POS Shift',
                'verbose_name_plural': 'POS Shifts',
                'ordering': ['-opened_at'],
                'permissions': [('can_manage_pos_shifts', 'Can Manage POS Shifts')],
            },
        ),
    ]
