# Generated by Django 4.2.7 on 2025-07-05 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_product_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر التكلفة'),
        ),
    ]
