# Generated by Django 4.2.7 on 2025-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, help_text='المنتجات الخدمية لا تؤثر على المخزون', verbose_name='منتج خدمي (غير معدود)'),
        ),
    ]
