# Generated by Django 4.2.7 on 2025-08-12 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Initial stock quantity when starting to use the system', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opening Balance'),
        ),
    ]
