# Generated by Django 4.2.7 on 2025-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, help_text='فعّل هذا الخيار إذا كان المنتج عبارة عن خدمة وليس منتجاً مادياً', verbose_name='هل هو خدمة'),
        ),
    ]
