# Generated by Django 4.2.7 on 2025-08-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_service',
        ),
    ]
