# Generated by Django 4.2.7 on 2025-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_is_service_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'سلعة'), ('service', 'خدمة')], default='physical', max_length=20, verbose_name='نوع المنتج'),
        ),
    ]
