# Generated by Django 4.2.7 on 2025-09-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='الفئة'),
            preserve_default=False,
        ),
    ]
