# Generated by Django 4.2.7 on 2025-09-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_add_category_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence_number'], 'permissions': [('can_view_products', 'يمكن عرض الفئات والمنتجات')], 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code', 'name'], 'permissions': [('can_view_products', 'يمكن عرض الفئات والمنتجات')], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
