# Generated by Django 4.2.7 on 2025-09-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence_number'], 'permissions': [('can_view_products', 'يمكن عرض الفئات والمنتجات'), ('can_add_products', 'يمكن إضافة المنتجات'), ('can_edit_products', 'يمكن تعديل المنتجات'), ('can_add_categories', 'يمكن إضافة الفئات'), ('can_edit_categories', 'يمكن تعديل الفئات'), ('can_delete_categories', 'يمكن حذف الفئات'), ('can_delete_products', 'يمكن حذف المنتجات')], 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code', 'name'], 'permissions': [('can_view_products', 'يمكن عرض الفئات والمنتجات'), ('can_add_products', 'يمكن إضافة المنتجات'), ('can_edit_products', 'يمكن تعديل المنتجات'), ('can_add_categories', 'يمكن إضافة الفئات'), ('can_edit_categories', 'يمكن تعديل الفئات'), ('can_delete_categories', 'يمكن حذف الفئات'), ('can_delete_products', 'يمكن حذف المنتجات')], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
