# Generated by Django 4.2.7 on 2025-09-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_add_can_edit_products_permission'),
    ]

    operations = [
    ]
