# Generated by Django 4.2.7 on 2025-09-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_add_edit_products_permission'),
        ('products', '0023_add_edit_products_permission'),
    ]

    operations = [
    ]
