# Generated by Django 4.2.7 on 2025-09-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_category_code_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence_number'], 'permissions': [('can_view_products', 'يمكن عرض الفئات والمنتجات'), ('can_add_products', 'يمكن إضافة المنتجات'), ('can_edit_products', 'يمكن تعديل المنتجات'), ('can_add_categories', 'يمكن إضافة الفئات'), ('can_add_categories_inline', 'يمكن إضافة الفئات من خلال النوافذ المنبثقة'), ('can_edit_categories', 'يمكن تعديل الفئات'), ('can_delete_categories', 'يمكن حذف الفئات'), ('can_delete_products', 'يمكن حذف المنتجات')], 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
    ]
