# Generated by Django 4.2.7 on 2025-10-07 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_balance_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_balance_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='كمية الرصيد الافتتاحي'),
        ),
    ]
