# Generated by Django 4.2.7 on 2025-10-11 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_opening_balance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأقصى للكمية'),
        ),
    ]
