# Generated by Django 4.2.7 on 2025-10-12 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorymovement_product_and_more'),
        ('products', '0028_product_image_product_maximum_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_balance_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='مستودع الرصيد الافتتاحي'),
        ),
    ]
