# Generated by Django 4.2.7 on 2025-11-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_opening_balance_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sequence_number'], 'permissions': [('can_view_products', 'يمكن عرض الفئات والمنتجات'), ('can_add_products', 'يمكن إضافة المنتجات'), ('can_edit_products', 'يمكن تعديل المنتجات'), ('can_delete_products', 'يمكن حذف المنتجات'), ('can_add_categories', 'يمكن إضافة الفئات'), ('can_add_categories_inline', 'يمكن إضافة الفئات من خلال النوافذ المنبثقة'), ('can_edit_categories', 'يمكن تعديل الفئات'), ('can_delete_categories', 'يمكن حذف الفئات')], 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'ordering': ['code', 'name'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
