# Generated by Django 4.2.7 on 2025-11-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': [], 'ordering': ['sequence_number'], 'permissions': [('can_view_products', 'Can View Products'), ('can_add_products', 'Can Add Products'), ('can_edit_products', 'Can Edit Products'), ('can_delete_products', 'Can Delete Products'), ('can_view_product_categories', 'Can View Product Categories'), ('can_add_product_categories', 'Can Add Product Categories'), ('can_edit_product_categories', 'Can Edit Product Categories'), ('can_delete_product_categories', 'Can Delete Product Categories')], 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
    ]
