# Generated by Django 4.2.7 on 2025-11-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'ordering': ['sequence_number', 'code', 'name'], 'permissions': [('can_edit_product_sequence_number', 'Can Edit Product Sequence Number')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Sequence Number'),
        ),
    ]
