# Generated by Django 4.2.7 on 2025-11-30 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_options_product_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Number of single units in one package', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conversion Factor'),
        ),
        migrations.AddField(
            model_name='product',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='The linked product (single or package)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_units', to='products.product', verbose_name='Linked Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('single', 'Single Unit'), ('package', 'Package'), ('standalone', 'Standalone')], default='standalone', help_text='Type of unit: single (individual), package (bulk), or standalone (not linked)', max_length=20, verbose_name='Unit Type'),
        ),
    ]
