# Generated by Django 4.2.7 on 2025-12-27 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_add_linked_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_balance_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Cost per unit for opening balance', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opening Balance Unit Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='opening_balance_cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Total opening balance cost (auto-calculated)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opening Balance Cost'),
        ),
    ]
