# Generated by Django 4.2.7 on 2025-12-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_product_opening_balance_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
    ]
